---
title: "gameloganim"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(fuzzyjoin)
library(stringr)
library(ggthemes)
library(ggrepel)
library(extrafont)
library(hrbrthemes)
library(xkcd)
library(cowplot)
library(magick)
library(zoo)
library(gganimate)
library(ggimage)
library(beeswarm)
library(DescTools)
library(ggbeeswarm)
library(reshape2)
library(RColorBrewer)

nhl = read_csv("gamelog20189.csv") 
```

```{r}
library(extrafont)
```


```{r}
standings = nhl %>% 
  mutate(winner = case_when(HG>VG ~ Home,
                            HG<VG ~ Visitor),
         loser = case_when(VG>HG ~ Home,
                            VG<HG ~ Visitor)) %>% 
  mutate(OTloser = case_when(OT == "OT" | OT == "SO" ~ loser,
                             TRUE ~ "None")) %>% 
  select(Date, winner, loser, OTloser) %>% 
  gather(winner, loser, key = "type", value = "team") %>% 
  mutate(Points = case_when(type == "winner" ~ 2,
                            type == "loser" ~ 0,
                            type == "OTloser" ~ 1)) %>% 
  mutate(Date = lubridate::mdy(Date)) %>% 
  arrange(Date) %>% 
  mutate(Points = case_when(OTloser == team ~ 1, TRUE ~ Points)) %>% 
  group_by(team, Date) %>% 
  summarize(total = cumsum(Points)) %>% 
  mutate(cumsum = cumsum(total)) %>% 
  mutate(game = row_number()) %>% 
   mutate(game = as.numeric(game)) %>% 
  ungroup() %>% 
  filter(team %in% atlantic) %>% 
  mutate(team = fct_reorder(team, cumsum, .fun = max, .desc = TRUE))

animate = standings %>% 
  ggplot(aes(game, cumsum, group = team, color = team)) +
  geom_line(size = 1) +
  transition_reveal(Date) +
  geom_label_repel(aes(label = team), force = 0, box.padding = 0, label.padding = 0.2, label.size = 0.2) +
  theme_ipsum_rc() +
  theme(legend.position = "none") +
  labs(title = "The Lightning's Dominant Season, Animated", subtitle = "2018-19 Point Totals", x = "Games", y = "Points") +
  scale_x_continuous(breaks = seq(0,82, by = 10))

animate(animate, end_pause = 30)

anim_save("tampa.gif")


```

```{r}
atlantic = c("Toronto Maple Leafs", "Boston Bruins", "Tampa Bay Lightning", "Florida Panthers", "Buffalo Sabres", "Montreal Canadiens", "Detroit Red Wings", "Ottawa Senators")

colors = c("#002868", "#FFB81C", "#00205B", "#AF1E2D", "#B9975B", "#002654", "#CE1126")

stan = standings %>% 
  ggplot(aes(game, cumsum)) +
  geom_line(size = 2, color = "grey") +
  geom_area(aes(fill = team), alpha = 0.6) +
  facet_wrap(~team) +
  scale_y_continuous(breaks = c(0,40,80,120)) +
  xlim(0,95) +
  theme_fivethirtyeight() +
  theme(legend.position = "none") +
  geom_text(data = standings %>% filter(game == 82, team %in% atlantic), aes(label = cumsum, color = team, fontface=2), hjust = -0.1) +
  labs(title = "Tampa, Boston, and Toronto led the Atlantic", subtitle = "Atlantic Hockey Standings '18-'19", y = "Points", caption = "Chart by @MackinawStats") +
  transition_reveal(game) +
  theme(axis.title = element_text()) + xlab('Games')

animate(stan, end_pause = 45)
anim_save("standings.gif")
```

