---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#colors

#palettes
#'primary color palette
#' @export
ppalette<-c('#F7DC05','#3d98d3','#EC0B88','#5e35b1','#f9791e','#3dd378','#c6c6c6','#444444')
#'secondary color palette
#' @export
spalette<-c('#9F248F','#FFCE4E','#017a4a','#f9791e','#244579','#c6242d')
#'flat
#' @export
mpalette<-c('#017a4a','#FFCE4E','#3d98d3','#ff363c','#7559a2','#794924','#8cdb5e','#d6d6d6','#fb8c00')
#'original
#' @export
a_palette<-c('#2A363B','#019875','#99B898','#FECEA8','#FF847C','#E84A5F','#C0392B','#96281B')
#'grays
#' @export
gpalette<-c('#d6d6d6','#adadad','#707070','#333333') 
#'big color palette
#' @export
bpalette<-c('#c62828','#f44336','#9c27b0','#673ab7','#3f51b5','#2196f3','#29b6f6','#006064','#009688','#4caf50','#8bc34a','#ffeb3b','#ff9800','#795548','#9e9e9e','#607d8b')


#' Original color palette with decent brightness
#'
#' @export
#' @examples
#' library(scales)
#' scales::show_col(a_pal()(8))
a_pal <- function() {scales::manual_pal(a_palette) }

#' @md
#' @export
a_scale_colour <- function(...) { discrete_scale("colour", "a", a_pal(), ...) }
#' @md
#' @export
a_scale_color<-a_scale_colour
#' @md
#' @export
a_scale_fill <- function(...) { discrete_scale("fill", "a", a_pal(), ...) }

#' Big color palette
#'
#' @export
#' @examples
#' library(scales)
#' scales::show_col(b_pal()(8))
b_pal <- function() {scales::manual_pal(bpalette) }

#' @md
#' @export
b_scale_colour <- function(...) { discrete_scale("colour", "a", b_pal(), ...) }
#' @md
#' @export
b_scale_color<-b_scale_colour
#' @md
#' @export
b_scale_fill <- function(...) { discrete_scale("fill", "a", b_pal(), ...) }


#' Primary color palette with decent brightness
#'
#' @export
#' @examples
#' library(scales)
#' scales::show_col(p_pal()(8))
p_pal<- function() { scales::manual_pal(ppalette) }
#' @md
#' @export
a_primary_colour <- function(...) { discrete_scale("colour", "a", p_pal(), ...) }
#' @md
#' @export
a_primary_color<-a_primary_colour
#' @md
#' @export
a_primary_fill <- function(...) { discrete_scale("fill", "a", p_pal(), ...) }

#' Secondary color palette
#secondary color palette
#' @export
s_pal<- function() { scales::manual_pal(spalette)}
#' @export
a_secondary_colour <- function(...) { discrete_scale("colour", "a", s_pal(), ...) }
#' @export
a_secondary_color<-a_secondary_colour
#' @export
a_secondary_fill <- function(...) { discrete_scale("fill", "a", s_pal(), ...) }


#' Flat color palette (see readme)
#' @export
m_pal<- function() { scales::manual_pal(mpalette)}
#' flat color palette (see readme)
#' @export
a_flat_colour <- function(...) { discrete_scale("colour", "a", m_pal(), ...) }
#' flat color palette (see readme)
#' @export
a_flat_color<-a_flat_colour
#' flat color palette (see readme)
#' @export
a_flat_fill <- function(...) { discrete_scale("fill", "a", m_pal(), ...) }

#' Sort of sequential gray palette
#' @export
#' @examples
#' library(scales)
#' scales::show_col(g_pal()(4))
g_pal<- function() { scales::manual_pal(gpalette)}
#' @export
a_gray_colour <- function(...) { discrete_scale("colour", "a", g_pal(), ...) }
#' @export
a_gray_color<-a_gray_colour
#' @export
a_gray_fill <- function(...) { discrete_scale("fill", "a", g_pal(), ...) }
```

```{r}
#functions
#functions start
#simple function to replace NAs with 0
#' Remove NAs function 
#' @param df dataframe object
#' @param cols column(s) to remove NA and replace with 0
#' @keywords NA
#' @export
#' @examples \dontrun{
#' removeNAs(df,cols)
removeNAs<-function(df,cols){
  apply(df[,cols], 2, function(x){replace(x, is.na(x), 0)})
}

#function to return the column with the max value (or value of function provided)
#' Function to return the column with the max value (or value of function provided)
#' @param df dataframe object
#' @param cols column(s) to remove NA and replace with 0
#' @param fun operator function to apply across columns, defaults to max
#' @keywords max value
#' @export
#' @examples \dontrun{
#' col_compare(df,cols)
col_compare<-function(df,cols,fun=which.max){
  x<-data.frame(df)
  temp<-x[,c(cols)]
  wins<-colnames(temp)[apply(temp,1,fun)]
  return(wins)
}

#Chart formatting functions
#'for use with axis labels, returns absolute value with commas
#' @export
abs_comma <- function (x, ...) {
  format(abs(x), ..., big.mark = ",", scientific = FALSE, trim = TRUE)
}

#abbrev. function
#from https://stackoverflow.com/questions/28159936/formatting-large-currency-or-dollar-values-to-millions-billions/28160040
#'for use with axis labels turns big number into abbrev. form
#' @export
m.compress <- function(tx) { 
  div <- findInterval(as.numeric(gsub("\\,", "", tx)), 
                      c(1, 1e3, 1e6, 1e9, 1e12) )
  paste(round( as.numeric(gsub("\\,","",tx))/10^(3*(div-1)), 2), 
        c("","K","M","B","T")[div] )} 
```

```{r}
#old
#' All of the themes follow a similar pattern mainly just changing out font families 
#' and small tweaks to plot elements
#' 
#' a_theme / a_concert_theme / a_robot_theme are all mostly unused now
#' 
#' 
#' @md
#' @param base_family,base_size base font family and size
#' @param plot_title_family,plot_title_face,plot_title_size plot title family, face, size 
#' @param subtitle_family,subtitle_face,subtitle_size plot subtitle family, face and size
#' @param strip_text_family,strip_text_face,strip_text_size facet label font family, face and size
#' @param caption_family,caption_face,caption_size plot caption family, face, size 
#' @param axis_title_family,axis_title_face,axis_title_size axis title font family, face and size
#' @param axis_text_size size of axis text labels
#' @param grid_col grid & axis colors; both default to `#cccccc`
#' @param grid panel grid (`TRUE`, `FALSE`, or a combination of `X`, `x`, `Y`, `y`)
#' @param noaxis include/exclude axis (`TRUE`, `FALSE`, or a combination of `X`, `x`, `Y`, `y`)
#' @param emphasis bold one axis title of both (a combination of 'x','y' or 'xy') 
#' @param rotate_x TRUE/FAlSE to rotate axis text
#' @export
#' @examples \dontrun{
#' library(ggplot2)
#' library(dplyr)
#'
#' # scatterplot
#' ggplot(mtcars, aes(mpg, wt)) +
#'   geom_point() +
#'   labs(title="mtcars example") +
#'   a_theme()
a_theme<- function(
  base_family="Roboto",
  base_size = 10,
  plot_title_family='Open Sans',
  plot_title_size = 18,
  plot_title_face="bold",
  subtitle_family=base_family,
  subtitle_size = 10,
  subtitle_face = "plain",
  strip_text_family = base_family,
  strip_text_size = 10,
  strip_text_face = "plain",
  caption_family= base_family,
  caption_size = 10,
  caption_face = "plain",
  axis_text_size = base_size,
  axis_title_family = plot_title_family,
  axis_title_size = 10,
  axis_title_face = "plain",
  grid_col='#dedede',
  grid=TRUE,
  noaxis=FALSE,
  emphasis='xy',
  rotate_x=FALSE)
{
  aplot <- ggplot2::theme_minimal(base_family=base_family, base_size=base_size)
  
  if (inherits(grid, "character") | grid == TRUE) {
    
    aplot <- aplot + theme(panel.grid=element_line(color=grid_col, size=0.2))
    aplot <- aplot + theme(panel.grid.major=element_line(color=grid_col, size=0.2))
    aplot <- aplot + theme(panel.grid.minor=element_line(color=grid_col, size=0.15))
    
    
    if (inherits(grid, "character")) {
      if (regexpr("X", grid)[1] < 0) aplot <- aplot + theme(panel.grid.major.x=element_blank())
      if (regexpr("Y", grid)[1] < 0) aplot <- aplot + theme(panel.grid.major.y=element_blank())
      if (regexpr("x", grid)[1] < 0) aplot <- aplot + theme(panel.grid.minor.x=element_blank())
      if (regexpr("y", grid)[1] < 0) aplot <- aplot + theme(panel.grid.minor.y=element_blank())
    }
    
  } else {
    aplot <- aplot + theme(panel.grid=element_blank())
  }
  if (inherits(grid, "character") | rotate_x == TRUE) {
    aplot<-aplot+theme(axis.text.x = element_text(angle = 90, hjust = 1))
  } 
  
  aplot <- aplot + theme(legend.background=element_blank())
  aplot <- aplot + theme(legend.key=element_blank())
  if (inherits(grid, "character") | noaxis == TRUE) {
    aplot <- aplot + theme(axis.text.x=element_blank())
    aplot <- aplot + theme(axis.text.y=element_blank())}
  else{
    aplot <- aplot + theme(axis.text.x=element_text(size=axis_text_size,family=subtitle_family,face = dplyr::case_when(emphasis=='x' ~'bold',emphasis=='y'~'plain',emphasis=='xy'~'plain'),color='#444444'))
    aplot <- aplot + theme(axis.text.y=element_text(size=axis_text_size,family=subtitle_family,face = dplyr::case_when(emphasis=='y' ~'bold',emphasis=='x'~'plain',emphasis=='xy'~'plain'),color='#444444'))}
  aplot <- aplot + theme(axis.title=element_text(size=axis_title_size, family=axis_title_family))
  aplot <- aplot + theme(axis.title.x=element_text(size=axis_title_size, family=axis_title_family, face=axis_title_face, margin=margin(t = 18, b = 10, unit = "pt")))
  aplot <- aplot + theme(axis.title.y=element_text(size=axis_title_size, family=axis_title_family, face=axis_title_face,margin=margin(r = 18, unit = "pt")))
  aplot <- aplot + theme(strip.text=element_text(hjust=0, size=strip_text_size,face=strip_text_face, family=strip_text_family))
  aplot <- aplot + theme(panel.spacing=grid::unit(2, "lines"))
  aplot <- aplot + theme(plot.title=element_text(hjust=0, size=plot_title_size, family=plot_title_family, face=plot_title_face,color='#444444'))
  aplot <- aplot + theme(plot.subtitle=element_text(hjust=0, size=subtitle_size, margin=margin(t = 4, b = 12, unit = "pt"),family=subtitle_family, face=subtitle_face,color='#565656', lineheight=1))
  aplot <- aplot + theme(plot.caption=element_text(hjust=1, size=caption_size,  family=caption_family, face=caption_face,color='#565656'))
  aplot
  
}

#' All of the themes follow a similar pattern mainly just changing out font families 
#' and small tweaks to plot elements
#' 
#' a_theme / a_concert_theme / a_robot_theme are all mostly unused now
#' 
#' 
#' @md
#' @param base_family,base_size base font family and size
#' @param plot_title_family,plot_title_face,plot_title_size plot title family, face, size 
#' @param subtitle_family,subtitle_face,subtitle_size plot subtitle family, face and size
#' @param strip_text_family,strip_text_face,strip_text_size facet label font family, face and size
#' @param caption_family,caption_face,caption_size plot caption family, face, size 
#' @param axis_title_family,axis_title_face,axis_title_size axis title font family, face and size
#' @param grid_col grid & axis colors; both default to `#cccccc`
#' @param grid panel grid (`TRUE`, `FALSE`, or a combination of `X`, `x`, `Y`, `y`)
#' @param noaxis include/exclude axis (`TRUE`, `FALSE`, or a combination of `X`, `x`, `Y`, `y`)
#' @param emphasis bold one axis title of both (a combination of 'x','y' or 'xy') 
#' @param rotate_x TRUE/FAlSE to rotate axis text
#' @export
#' @examples \dontrun{
#' library(ggplot2)
#' library(dplyr)
#'
#' # scatterplot
#' ggplot(mtcars, aes(mpg, wt)) +
#'   geom_point() +
#'   labs(title="mtcars example") +
#'   a_robot_theme()

a_robot_theme<- function(
  base_family="Roboto",
  base_size = 10,
  plot_title_family='Roboto Slab',
  plot_title_size = 16,
  plot_title_face="plain",
  subtitle_family=base_family,
  subtitle_size = 10,
  subtitle_face = "plain",
  strip_text_family = base_family,
  strip_text_size = 12,
  strip_text_face = "plain",
  caption_family= base_family,
  caption_size = 10,
  caption_face = "plain",
  axis_text_size = base_size,
  axis_title_family = base_family,
  axis_title_size = 10,
  axis_title_face = "plain",
  grid_col='#dedede',
  grid=TRUE,
  noaxis=FALSE,
  emphasis='xy',
  rotate_x=FALSE)
{
  aplot <- ggplot2::theme_minimal(base_family=base_family, base_size=base_size)
  
  if (inherits(grid, "character") | grid == TRUE) {
    
    aplot <- aplot + theme(panel.grid=element_line(color=grid_col, size=0.2))
    aplot <- aplot + theme(panel.grid.major=element_line(color=grid_col, size=0.2))
    aplot <- aplot + theme(panel.grid.minor=element_line(color=grid_col, size=0.15))
    
    
    if (inherits(grid, "character")) {
      if (regexpr("X", grid)[1] < 0) aplot <- aplot + theme(panel.grid.major.x=element_blank())
      if (regexpr("Y", grid)[1] < 0) aplot <- aplot + theme(panel.grid.major.y=element_blank())
      if (regexpr("x", grid)[1] < 0) aplot <- aplot + theme(panel.grid.minor.x=element_blank())
      if (regexpr("y", grid)[1] < 0) aplot <- aplot + theme(panel.grid.minor.y=element_blank())
    }
    
  } else {
    aplot <- aplot + theme(panel.grid=element_blank())
  }
  if (inherits(grid, "character") | rotate_x == TRUE) {
    aplot<-aplot+theme(axis.text.x = element_text(angle = 90, hjust = 1))
  } 
  
  aplot <- aplot + theme(legend.background=element_blank())
  aplot <- aplot + theme(legend.key=element_blank())
  if (inherits(grid, "character") | noaxis == TRUE) {
    aplot <- aplot + theme(axis.text.x=element_blank())
    aplot <- aplot + theme(axis.text.y=element_blank())}
  else{
    aplot <- aplot + theme(axis.text.x=element_text(size=axis_text_size,family=subtitle_family,face = dplyr::case_when(emphasis=='x' ~'bold',emphasis=='y'~'plain',emphasis=='xy'~'plain'),color='#444444'))
    aplot <- aplot + theme(axis.text.y=element_text(size=axis_text_size,family=subtitle_family,face = dplyr::case_when(emphasis=='y' ~'bold',emphasis=='x'~'plain',emphasis=='xy'~'plain'),color='#444444'))}
  aplot <- aplot + theme(axis.title=element_text(size=axis_title_size, family=axis_title_family))
  aplot <- aplot + theme(axis.title.x=element_text(size=axis_title_size, family=axis_title_family, face=axis_title_face, margin=margin(t = 18, b = 10, unit = "pt")))
  aplot <- aplot + theme(axis.title.y=element_text(size=axis_title_size, family=axis_title_family, face=axis_title_face,margin=margin(r = 18, unit = "pt")))
  aplot <- aplot + theme(strip.text=element_text(hjust=0, size=strip_text_size,face=strip_text_face, family=strip_text_family))
  aplot <- aplot + theme(panel.spacing=grid::unit(2, "lines"))
  aplot <- aplot + theme(plot.title=element_text(hjust=0, size=plot_title_size, family=plot_title_family, face=plot_title_face,color='#444444'))
  aplot <- aplot + theme(plot.subtitle=element_text(hjust=0, size=subtitle_size, margin=margin(t = 8, b = 12, unit = "pt"),family=subtitle_family, face=subtitle_face,color='#565656', lineheight=1))
  aplot <- aplot + theme(plot.caption=element_text(hjust=1, size=caption_size,  family=caption_family, face=caption_face,color='#565656'))
  aplot
  
}

#' All of the themes follow a similar pattern mainly just changing out font families 
#' and small tweaks to plot elements
#' 
#' a_theme / a_concert_theme / a_robot_theme are all mostly unused now
#' 
#' 
#' @md
#' @param base_family,base_size base font family and size
#' @param plot_title_family,plot_title_face,plot_title_size plot title family, face, size 
#' @param subtitle_family,subtitle_face,subtitle_size plot subtitle family, face and size
#' @param strip_text_family,strip_text_face,strip_text_size facet label font family, face and size
#' @param caption_family,caption_face,caption_size plot caption family, face, size 
#' @param axis_title_family,axis_title_face,axis_title_size axis title font family, face and size
#' @param grid_col,axis_col grid & axis colors; both default to `#cccccc`
#' @param grid panel grid (`TRUE`, `FALSE`, or a combination of `X`, `x`, `Y`, `y`)
#' @param noaxis include/exclude axis (`TRUE`, `FALSE`, or a combination of `X`, `x`, `Y`, `y`)
#' @param emphasis bold one axis title of both (a combination of 'x','y' or 'xy') 
#' @param rotate_x TRUE/FAlSE to rotate axis text
#' @export
#' @examples \dontrun{
#' library(ggplot2)
#' library(dplyr)
#'
#' # scatterplot
#' ggplot(mtcars, aes(mpg, wt)) +
#'   geom_point() +
#'   labs(title="mtcars example") +
#'   a_concert_theme()
#concert
a_concert_theme<- function(
  base_family="Inconsolata",
  base_size = 10,
  plot_title_family='Concert One',
  plot_title_size = 25,
  plot_title_face="bold",
  subtitle_family=base_family,
  subtitle_size = 10,
  subtitle_face = "plain",
  strip_text_family = base_family,
  strip_text_size = 12,
  strip_text_face = "plain",
  caption_family= base_family,
  caption_size = 10,
  caption_face = "plain",
  axis_text_size = base_size,
  axis_title_family = plot_title_family,
  axis_title_size = 12,
  axis_title_face = "plain",
  grid_col='#dedede',
  grid=TRUE,
  noaxis=FALSE,
  emphasis='xy',
  rotate_x=FALSE)
{
  aplot <- ggplot2::theme_minimal(base_family=base_family, base_size=base_size)
  
  if (inherits(grid, "character") | grid == TRUE) {
    
    aplot <- aplot + theme(panel.grid=element_line(color=grid_col, size=0.2))
    aplot <- aplot + theme(panel.grid.major=element_line(color=grid_col, size=0.2))
    aplot <- aplot + theme(panel.grid.minor=element_line(color=grid_col, size=0.15))
    
    
    if (inherits(grid, "character")) {
      if (regexpr("X", grid)[1] < 0) aplot <- aplot + theme(panel.grid.major.x=element_blank())
      if (regexpr("Y", grid)[1] < 0) aplot <- aplot + theme(panel.grid.major.y=element_blank())
      if (regexpr("x", grid)[1] < 0) aplot <- aplot + theme(panel.grid.minor.x=element_blank())
      if (regexpr("y", grid)[1] < 0) aplot <- aplot + theme(panel.grid.minor.y=element_blank())
    }
    
  } else {
    aplot <- aplot + theme(panel.grid=element_blank())
  }
  if (inherits(grid, "character") | rotate_x == TRUE) {
    aplot<-aplot+theme(axis.text.x = element_text(angle = 90, hjust = 1))
  } 
  
  aplot <- aplot + theme(legend.background=element_blank())
  aplot <- aplot + theme(legend.key=element_blank())
  if (inherits(grid, "character") | noaxis == TRUE) {
    aplot <- aplot + theme(axis.text.x=element_blank())
    aplot <- aplot + theme(axis.text.y=element_blank())}
  else{
    aplot <- aplot + theme(axis.text.x=element_text(size=axis_text_size,family=subtitle_family,face = dplyr::case_when(emphasis=='x' ~'bold',emphasis=='y'~'plain',emphasis=='xy'~'plain'),color='#444444'))
    aplot <- aplot + theme(axis.text.y=element_text(size=axis_text_size,family=subtitle_family,face = dplyr::case_when(emphasis=='y' ~'bold',emphasis=='x'~'plain',emphasis=='xy'~'plain'),color='#444444'))}
  aplot <- aplot + theme(axis.title=element_text(size=axis_title_size, family=axis_title_family,color='#444444'))
  aplot <- aplot + theme(axis.title.x=element_text(size=axis_title_size, family=axis_title_family, face=axis_title_face, margin=margin(t = 18, b = 10, unit = "pt")))
  aplot <- aplot + theme(axis.title.y=element_text(size=axis_title_size, family=axis_title_family, face=axis_title_face,margin=margin(r = 18, unit = "pt")))
  aplot <- aplot + theme(strip.text=element_text(hjust=0, size=strip_text_size,face=strip_text_face, family=strip_text_family))
  aplot <- aplot + theme(panel.spacing=grid::unit(2, "lines"))
  aplot <- aplot + theme(plot.title=element_text(hjust=0, size=plot_title_size, family=plot_title_family, face=plot_title_face,color='#444444'))
  aplot <- aplot + theme(plot.subtitle=element_text(hjust=0, size=subtitle_size, margin=margin(t = 4, b = 12, unit = "pt"),family=subtitle_family, face=subtitle_face,color='#565656', lineheight=1))
  aplot <- aplot + theme(plot.caption=element_text(hjust=1, size=caption_size,  family=caption_family, face=caption_face,color='#565656'))
  aplot
}
```

```{r}
#' All of the themes follow a similar pattern mainly just changing out font families 
#' and small tweaks to plot elements
#' 
#' The main two are a_plex_theme / a_dark_theme which is a dark version of a_plex_theme
#' 
#' 
#' @md
#' @param base_family,base_size base font family and size
#' @param plot_title_family,plot_title_face,plot_title_size plot title family, face, size 
#' @param subtitle_family,subtitle_face,subtitle_size plot subtitle family, face and size
#' @param strip_text_family,strip_text_face,strip_text_size facet label font family, face and size
#' @param caption_family,caption_face,caption_size plot caption family, face, size 
#' @param axis_title_family,axis_title_face,axis_title_size axis title font family, face and size
#' @param grid_col,axis_col grid & axis colors; both default to `#cccccc`
#' @param grid panel grid (`TRUE`, `FALSE`, or a combination of `X`, `x`, `Y`, `y`)
#' @param noaxis include/exclude axis (`TRUE`, `FALSE`, or a combination of `X`, `x`, `Y`, `y`)
#' @param emphasis bold one axis title of both (a combination of 'x','y' or 'xy') 
#' @param rotate_x TRUE/FAlSE to rotate axis text
#' @export
#' @examples \dontrun{
#' library(ggplot2)
#' library(dplyr)
#'
#' # scatterplot
#' ggplot(mtcars, aes(mpg, wt)) +
#'   geom_point() +
#'   labs(title="mtcars example") +
#'   a_plex_theme()
#Plex
a_plex_theme<- function(
  base_family="IBM Plex Sans",
  base_size =9,
  plot_title_family='IBM Plex Mono',
  plot_title_size = 20,
  plot_title_face="bold",
  subtitle_family=base_family,
  subtitle_size = 10,
  subtitle_face = "plain",
  strip_text_family = base_family,
  strip_text_size = 10,
  strip_text_face = "plain",
  caption_family= base_family,
  caption_size =9,
  caption_face = "plain",
  axis_text_size = base_size,
  axis_title_family = plot_title_family,
  axis_title_size = 10,
  axis_title_face = "plain",
  grid_col='#dedede',
  grid=TRUE,
  noaxis=FALSE,
  emphasis='xy',
  rotate_x=FALSE)
{
  aplot <- ggplot2::theme_minimal(base_family=base_family, base_size=base_size)
  
  if (inherits(grid, "character") | grid == TRUE) {
    
    aplot <- aplot + theme(panel.grid=element_line(color=grid_col, size=0.2))
    aplot <- aplot + theme(panel.grid.major=element_line(color=grid_col, size=0.2))
    aplot <- aplot + theme(panel.grid.minor=element_line(color=grid_col, size=0.15))
    
    
    if (inherits(grid, "character")) {
      if (regexpr("X", grid)[1] < 0) aplot <- aplot + theme(panel.grid.major.x=element_blank())
      if (regexpr("Y", grid)[1] < 0) aplot <- aplot + theme(panel.grid.major.y=element_blank())
      if (regexpr("x", grid)[1] < 0) aplot <- aplot + theme(panel.grid.minor.x=element_blank())
      if (regexpr("y", grid)[1] < 0) aplot <- aplot + theme(panel.grid.minor.y=element_blank())
    }
    
  } else {
    aplot <- aplot + theme(panel.grid=element_blank())
  }
  if (inherits(grid, "character") | rotate_x == TRUE) {
    aplot<-aplot+theme(axis.text.x = element_text(angle = 90, hjust = 1))
  } 
  
  aplot <- aplot + theme(legend.background=element_blank())
  aplot <- aplot + theme(legend.key=element_blank())
  if (inherits(grid, "character") | noaxis == TRUE) {
    aplot <- aplot + theme(axis.text.x=element_blank())
    aplot <- aplot + theme(axis.text.y=element_blank())}
  else{
    aplot <- aplot + theme(axis.text.x=element_text(size=axis_text_size,family=subtitle_family,face = dplyr::case_when(emphasis=='x' ~'bold',emphasis=='y'~'plain',emphasis=='xy'~'plain'),color='#444444'))
    aplot <- aplot + theme(axis.text.y=element_text(size=axis_text_size,family=subtitle_family,face = dplyr::case_when(emphasis=='y' ~'bold',emphasis=='x'~'plain',emphasis=='xy'~'plain'),color='#444444'))}
  aplot <- aplot + theme(axis.title=element_text(size=axis_title_size, family=axis_title_family,color='#444444'))
  aplot <- aplot + theme(axis.title.x=element_text(size=axis_title_size, family=axis_title_family, face=axis_title_face, margin=margin(t = 18, b = 10, unit = "pt")))
  aplot <- aplot + theme(axis.title.y=element_text(size=axis_title_size, family=axis_title_family, face=axis_title_face,margin=margin(r = 18, unit = "pt")))
  aplot <- aplot + theme(strip.text=element_text(hjust=0, size=strip_text_size,face=strip_text_face, family=strip_text_family))
  aplot <- aplot + theme(panel.spacing=grid::unit(2, "lines"))
  aplot <- aplot + theme(plot.title=element_text(hjust=0, size=plot_title_size, family=plot_title_family, face=plot_title_face,color='#444444'))
  aplot <- aplot + theme(plot.subtitle=element_text(hjust=0, size=subtitle_size, margin=margin(t = 4, b = 12, unit = "pt"),family=subtitle_family, face=subtitle_face,color='#565656', lineheight=1))
  aplot <- aplot + theme(plot.caption=element_text(hjust=1, size=caption_size,  family=caption_family, face=caption_face,color='#565656'))
  aplot
}

#' All of the themes follow a similar pattern mainly just changing out font families 
#' and small tweaks to plot elements
#' 
#' The main two are a_plex_theme / a_dark_theme which is a dark version of a_plex_theme
#' These two use IBM Plex Mono for title text and IBM Plex Sans for the rest
#' 
#' @md
#' @param base_family,base_size base font family and size
#' @param plot_title_family,plot_title_face,plot_title_size plot title family, face, size 
#' @param subtitle_family,subtitle_face,subtitle_size plot subtitle family, face and size
#' @param strip_text_family,strip_text_face,strip_text_size facet label font family, face and size
#' @param caption_family,caption_face,caption_size plot caption family, face, size 
#' @param axis_title_family,axis_title_face,axis_title_size axis title font family, face and size
#' @param grid_col,axis_col grid & axis colors; both default to `#cccccc`
#' #' @param shade is a parameter to change the plot background color defaults to `#1d1d1d`
#' @param grid panel grid (`TRUE`, `FALSE`, or a combination of `X`, `x`, `Y`, `y`)
#' @param noaxis include/exclude axis (`TRUE`, `FALSE`, or a combination of `X`, `x`, `Y`, `y`)
#' @param emphasis bold one axis title of both (a combination of 'x','y' or 'xy') 
#' @param rotate_x TRUE/FAlSE to rotate axis text
#' @export
#' @examples \dontrun{
#' library(ggplot2)
#' library(dplyr)
#'
#' # scatterplot
#' ggplot(mtcars, aes(mpg, wt)) +
#'   geom_point() +
#'   labs(title="mtcars example") +
#'   a_dark_theme()

#Dark Plex
a_dark_theme<- function(
  base_family="IBM Plex Sans",
  base_size =9,
  plot_title_family='IBM Plex Mono',
  plot_title_size = 20,
  plot_title_face="bold",
  subtitle_family=base_family,
  subtitle_size = 10,
  subtitle_face = "plain",
  strip_text_family = base_family,
  strip_text_size = 10,
  strip_text_face = "plain",
  caption_family= base_family,
  caption_size = 9,
  caption_face = "plain",
  axis_text_size = base_size,
  axis_title_family = plot_title_family,
  axis_title_size = 10,
  axis_title_face = "plain",
  grid_col='#555555',
  shade='#1d1d1d',
  grid=TRUE,
  noaxis=FALSE,
  emphasis='xy',
  rotate_x=FALSE)
{
  aplot <- ggplot2::theme_minimal(base_family=base_family, base_size=base_size)
  
  if (inherits(grid, "character") | grid == TRUE) {
    
    aplot <- aplot + theme(panel.grid=element_line(color=grid_col, size=0.2))
    aplot <- aplot + theme(panel.grid.major=element_line(color=grid_col, size=0.2))
    aplot <- aplot + theme(panel.grid.minor=element_line(color=grid_col, size=0.15))
    
    
    if (inherits(grid, "character")) {
      if (regexpr("X", grid)[1] < 0) aplot <- aplot + theme(panel.grid.major.x=element_blank())
      if (regexpr("Y", grid)[1] < 0) aplot <- aplot + theme(panel.grid.major.y=element_blank())
      if (regexpr("x", grid)[1] < 0) aplot <- aplot + theme(panel.grid.minor.x=element_blank())
      if (regexpr("y", grid)[1] < 0) aplot <- aplot + theme(panel.grid.minor.y=element_blank())
    }
    
  } else {
    aplot <- aplot + theme(panel.grid=element_blank())
  }
  if (inherits(grid, "character") | rotate_x == TRUE) {
    aplot<-aplot+theme(axis.text.x = element_text(angle = 90, hjust = 1))
  } 
  
  aplot <- aplot + theme(legend.background=element_blank())
  aplot <- aplot + theme(legend.key=element_blank())
  aplot <- aplot + theme(legend.text=element_text(family=plot_title_family,color='#e3e3e3'),
                         legend.title=element_text(family=plot_title_family,color='#e3e3e3'))
  if (inherits(grid, "character") | noaxis == TRUE) {
    aplot <- aplot + theme(axis.text.x=element_blank())
    aplot <- aplot + theme(axis.text.y=element_blank())}
  else{
    aplot <- aplot + theme(axis.text.x=element_text(size=axis_text_size,family=subtitle_family,face = dplyr::case_when(emphasis=='x' ~'bold',emphasis=='y'~'plain',emphasis=='xy'~'plain'),color='#e3e3e3'))
    aplot <- aplot + theme(axis.text.y=element_text(size=axis_text_size,family=subtitle_family,face = dplyr::case_when(emphasis=='y' ~'bold',emphasis=='x'~'plain',emphasis=='xy'~'plain'),color='#e3e3e3'))}
  aplot <- aplot + theme(axis.title=element_text(size=axis_title_size, family=axis_title_family,color='#e3e3e3'))
  aplot <- aplot + theme(axis.title.x=element_text(size=axis_title_size, family=axis_title_family, face=axis_title_face, margin=margin(t = 18, b = 10, unit = "pt")))
  aplot <- aplot + theme(axis.title.y=element_text(size=axis_title_size, family=axis_title_family, face=axis_title_face,margin=margin(r = 18, unit = "pt")))
  aplot <- aplot + theme(strip.text=element_text(hjust=0, size=strip_text_size,face=strip_text_face, family=strip_text_family, color='#e3e3e3'))
  aplot <- aplot + theme(panel.spacing=grid::unit(2, "lines"))
  aplot <- aplot + theme(plot.title=element_text(hjust=0, size=plot_title_size, family=plot_title_family, face=plot_title_face,color='#e3e3e3'))
  aplot <- aplot + theme(plot.subtitle=element_text(hjust=0, size=subtitle_size, margin=margin(t = 4, b = 12, unit = "pt"),family=subtitle_family, face=subtitle_face,color='#e3e3e3', lineheight=1))
  aplot <- aplot + theme(plot.caption=element_text(hjust=1, size=caption_size,  family=caption_family, face=caption_face,color='#808080'))
  aplot <- aplot + theme(plot.background = element_rect(fill = shade)) #plot background
  aplot <- aplot + theme(panel.background = element_rect(fill = shade,
                                                         colour = shade))
  aplot
}
```

