---
title: "animated"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(fuzzyjoin)
library(stringr)
library(ggthemes)
library(ggrepel)
library(extrafont)
library(hrbrthemes)
library(xkcd)
library(cowplot)
library(magick)
library(zoo)

Leafs = read_csv("https://raw.githubusercontent.com/hockeyfan22/mackinawstats/master/TOR.csv")
```

```{r}
Leafs %>% 
  mutate(minutes = iceTime/60) %>% 
  mutate(per60 = minutes/60) %>% 
  mutate(xGF = flurryScoreVenueAdjustedxGoalsFor/per60) %>% 
  mutate(xGA = flurryScoreVenueAdjustedxGoalsAgainst/per60) %>% 
  select(season,gameId,situation, xGF, xGA) %>% 
  filter(situation == "5on5") %>% 
  gather(xGF, xGA, key = "metric", value = "value") %>% 
  group_by(season,metric) %>% 
    summarize(value = mean(value)) %>% 
  ggplot(aes(season,value, group = metric, color = metric)) +
  geom_line(size = 2.5) + 
   theme_economist() +
theme(axis.line.x = element_line(size = .5, colour = "black"),
legend.position = "bottom", legend.direction = "horizontal",
legend.title = element_blank(),
plot.title = element_text(family = "Roboto Condensed"),
text = element_text(family = "Roboto Condensed")) +
guides(fill = guide_legend(reverse = T))+
  labs(title = "Expected Goals Percentage at 5v5", subtitle="Data from Moneypuck.com",x = "Year", y="Expected Goals For/Against Per 60") +
  theme(legend.position="none") +
  scale_x_continuous(breaks=c(2008,2010, 2012, 2014, 2016, 2018)) +
  expand_limits(y=1.8) +
  expand_limits(x= 2018.5) +
  transition_reveal(season) +
  geom_segment(aes(xend = 2018, yend = value), linetype = 2, colour = 'grey') +
   geom_text(aes(x = 2018, label = metric), hjust = 0, size = 5)

anim_save("leafs xG.gif")

  
```

