---
title: "contracts"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggbeeswarm)
```

```{r}
contracts = read_csv("contracts914.csv") %>% 
  mutate(caphitm = `Cap Hit`/1000000)
```
```{r}
contracts %>% 
  mutate(color = case_when(Tm == "TOR" & caphitm>10 ~ "TOR", TRUE ~ "None")) %>% 
  mutate(size = case_when(Tm == "TOR" & caphitm>10 ~ 2, TRUE ~ 1)) %>% 
  ggplot(aes(x=1, y = caphitm, color = color, size = size)) +
  scale_size(range = c(2, 3)) +
  scale_color_manual(values = c("grey","#00205B")) +
  geom_quasirandom(alpha = 0.4) +
  hrbrthemes::theme_ipsum_rc(grid = FALSE) +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x=element_blank()) +
  theme(legend.position = "none") +
  scale_y_continuous(breaks = c(2,4,6,8,10,12), labels = scales::dollar) +
  labs(title = "The Leafs Are Paying Up For Their Stars", subtitle = "NHL Salary Distribution - Cap Hit in $M, X axis set to 1", y = "Cap Hit ($M)", caption = "Chart by @MackinawStats")

ggsave("leafssalary.png")

```
geom_mark_hull(aes(filter = name %in% c("G. Murray", "J. Vardy"), label = "Vardy & Murray",
                        description = desc_vardymurray),
                    label.buffer = unit(20, "mm"), label.fontsize = c(14, 10),
                    label.family = "Roboto Condensed")
