---
title: "game1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(fuzzyjoin)
library(stringr)
library(ggthemes)
library(ggrepel)
library(extrafont)
library(hrbrthemes)
library(xkcd)
library(cowplot)
library(magick)
library(zoo)
library(gganimate)
library(ggimage)
library(beeswarm)
library(ggbeeswarm)

game1 = read_csv("game1.csv")
```
```{r}
game1 %>% 
  select(teamCode, time, event, xGoal, shotWasOnGoal) %>% 
  group_by(teamCode) %>% 
  mutate(cumxGoal = cumsum(xGoal)) %>% 
  mutate(time = time/60) %>% 
  ggplot(aes(time,cumxGoal, group = teamCode, color = teamCode)) + 
  geom_line(size = 1.5) +
  scale_color_manual(values = c("TOR" = "#003E7E", "BOS" = "#FFB81C")) +
  theme_fivethirtyeight() +
  labs(title = "Cumulative Expected Goals, Game 1 @ Boston", subtitle = "Data from Moneypuck.com") +
  transition_reveal(time) +
  theme(legend.position="none") 

anim_save("game1.gif")
  
```

