---
title: "radarchart"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(fuzzyjoin)
library(stringr)
library(ggthemes)
library(ggrepel)
library(extrafont)
library(hrbrthemes)
library(xkcd)
library(cowplot)
library(magick)
library(zoo)
library(gganimate)
library(ggimage)
library(beeswarm)
library(DescTools)
library(ggbeeswarm)
library(ggridges)
library(fmsb)
library(reshape2)
library(ggchicklet)

rapm = read_csv("rapmrates.csv")

war = read_csv("gar7.25.csv")

```
```{r}
rapm %>% 
  filter(Team == "TOR") %>% 
  select(player, GF_60, xGF_60, CF_60, xGA_60, CA_60) %>% 
  melt() %>% 
  mutate(player = fct_reorder(player, value, sum)) %>% 
  ggplot(aes(player, value, fill = variable)) +
  geom_chicklet(width = 0.75) +
  coord_flip() +
  theme_fivethirtyeight() +
  scale_fill_brewer() +
  theme(legend.position = "top")
```
```{r}
war %>% 
  filter(Team == "TOR") %>% 
  select(player, EV_GAR, Pens_GAR, PP_GAR, SH_GAR) %>% 
  melt() %>% 
  mutate(player = fct_reorder(player, value, sum)) %>% 
   ggplot(aes(player, value, fill = variable)) +
  geom_chicklet(width = 0.75) +
  coord_flip() +
  theme_fivethirtyeight() +
  scale_fill_manual(
    name = NULL,
    values = c(
      "EV_GAR" = "#ae4544",
      "Pens_GAR" = "#d8cb98",
      "PP_GAR" = "#a4ad6f",
      "SH_GAR" = "#436f82")) +
  theme_ipsum_rc(grid="X") +
  theme(axis.text.x = element_text(color = "gray60", size = 10)) +
  labs(title = "Goals Above Replacement, '16-19", x="", subtitle = "Data from @EvolvingHockey", caption = "Chart created by @MackinawStats") +
  theme(legend.position = "top")

ggsave("garbreak2.png")
```

```{r}
war2 = read_csv("gar3year.csv") %>% 
   filter(Team == "TOR") %>% 
  select(player, EV_GAR, Pens_GAR, PP_GAR, SH_GAR, position) %>% 
  melt() %>% 
  mutate(player = fct_reorder(player, value, sum))

war2 %>% 
  ggplot(aes(player, value, fill = variable)) +
  geom_chicklet(width = 0.75) +
  coord_flip() +
  theme_fivethirtyeight() +
  scale_fill_manual(
    name = NULL,
    values = c(
      "EV_GAR" = "#ae4544",
      "Pens_GAR" = "#d8cb98",
      "PP_GAR" = "#a4ad6f",
      "SH_GAR" = "#436f82")) +
  theme_ipsum_rc(grid="X") +
  theme(axis.text.x = element_text(color = "gray60", size = 10)) +
  labs(title = "Leafs Goals Above Replacement, '16-19", x="", subtitle = "Data from @EvolvingHockey", caption = "created by @MackinawStats", y = "") +
  theme(legend.position = "top")

ggsave("garbreakf.png")

```

