---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggthemes)
library(hrbrthemes)
library(showtext)
library(extrafont)
library(awtools)
```

```{r}
data = read_csv("dfa-networth-levels.csv")
```

```{r}
font_add_google("IBM Plex Mono", "IBM Plex Mono")
font_add_google("IBM Plex Sans", "IBM Plex Sans")

showtext_auto()
```


```{r}
data %>% 
  separate(col = Date, into = c("Year","Quarter"), sep = ":") %>% 
  filter(Year != "2019") %>% 
  filter(Category == "Top1" | Category == "Bottom50") %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Year, Category) %>% 
  summarize(networth = sum(`Net worth`)) %>% 
  mutate(Category = case_when(Category == "Bottom50" ~ "Bottom 50% Wealth",
                              Category == "Top1" ~ "Top 1% Wealth")) %>% 
  ggplot(aes(Year, networth, group = Category, fill = Category)) +
  geom_area() +
  facet_wrap(~Category) +
  scale_y_continuous(labels = scales::dollar) +
  theme_ipsum_ps(grid = FALSE) +
  labs(title = "Levels of Wealth by Percentile Groups", subtitle = "The Distributional Financial Accounts (DFAs) provide a quarterly measure of the distribution of U.S. household\nwealth since 1989, based on a comprehensive integration of disaggregated household-level wealth data\nwith official aggregate wealth measures.", y = "Net Worth", x = "") +
  theme(legend.position = "none")

ggsave("inequality.pdf", width = 12)
```

