---
title: "leafs contract blog post"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(fuzzyjoin)
library(stringr)
library(ggthemes)
library(ggrepel)
library(extrafont)
library(hrbrthemes)

NHL = read_csv(here("NHL.csv"), na = c("--","NA"))
leafs_contract = read_csv(here("leafs data.csv"))

#Filtering to Leafs 2019 season
leafs = NHL %>% 
  filter(Team == "TOR") %>% 
  filter(Season == 2019)

#Joining with contractual data
leafs = inner_join(leafs, leafs_contract, by = "Player")
leafs[is.na(leafs)] <- 0
leafs %>% 
  select(Player,Position,GP.x,TOI.x,G.x,A.x,P.x,CF,CA,`C+/-`,`CF%`,`Rel CF%`,`xGF`,`xGA`, `xG+/-`, `xGF%`,`PDO`, `AGE`, `CAP HIT`, `CAP HIT %`)


```


Points per contract dollar
```{r}
#leafs most productive players
leafs %>% 
  filter(`GP.x`>5) %>% 
  select(Player,`P.x`, `CAP HIT`) %>% 
  mutate(`CAP HIT` = `CAP HIT`/1000000) %>% 
  mutate(Pointpermillion = `P.x`/`CAP HIT`) %>% 
   arrange(desc(Pointpermillion)) %>% 
  head(10) %>% 
  mutate(Player = fct_reorder(Player, Pointpermillion)) %>% 
  ggplot(aes(Player,Pointpermillion, fill = Player)) + 
  geom_col() + 
  coord_flip() +
  labs(x="",y="Points per $1 million in Cap hit", title = "The leafs most productive players") +
  theme(legend.position="none")

leafs %>% 
  filter(`GP.x`>5) %>% 
  select(Player,`P.x`, `CAP HIT`) %>% 
  mutate(`CAP HIT` = `CAP HIT`/1000000) %>% 
  mutate(Pointpermillion = `P.x`/`CAP HIT`) %>% 
   arrange(Pointpermillion) %>% 
  head(10) %>% 
  mutate(Player = fct_reorder(Player,Pointpermillion,.desc = TRUE)) %>%
  ggplot(aes(Player,Pointpermillion, fill = Player)) + 
  geom_col() + 
  coord_flip()+
  labs(x = "",y="Points per $1 million in Cap hit", title = "Leafs least productive players") +
  theme(legend.position="none")

#taking TOI into account
leafs %>% 
  filter(`GP.x`>5) %>% 
  select(Player,`P.x`, `CAP HIT`,`P/60`) %>% 
  mutate(`CAP HIT` = `CAP HIT`/1000000) %>% 
  mutate(Pointpermillionper60 = `P/60`/`CAP HIT`) %>% 
   arrange(desc(Pointpermillionper60)) %>% 
  head(10) %>% 
  mutate(Player = fct_reorder(Player, Pointpermillionper60)) %>% 
  ggplot(aes(Player,Pointpermillionper60, fill = Player)) + 
  geom_col() + 
  coord_flip() +
  labs(x="",y="Points per 60 minutes TOI per $1 million in Cap hit", title = "The leafs most productive players with TOI") +
  theme(legend.position="none")

leafs %>% 
  filter(`GP.x`>5) %>% 
  select(Player,`P.x`, `CAP HIT`,`P/60`) %>% 
  mutate(`CAP HIT` = `CAP HIT`/1000000) %>% 
  mutate(Pointpermillionper60 = `P/60`/`CAP HIT`) %>% 
   arrange(Pointpermillionper60) %>% 
  head(10) %>% 
  mutate(Player = fct_reorder(Player, Pointpermillionper60,.desc = TRUE)) %>% 
  ggplot(aes(Player,Pointpermillionper60, fill = Player)) + 
  geom_col() + 
  coord_flip() +
  labs(x="",y="Points per 60 minutes TOI per $1 million in Cap hit", title = "The leafs least productive players with TOI") +
  theme(legend.position="none")

```

#let's take a look at Possession statistics
```{r}
#normalized the xG scale and compared to CFbins

leafs %>%
  mutate(CFbin = cut(`CF%`, c(37,46,48,52,Inf), labels = c("37-46","46-48","48-52","52+"))) %>% 
  mutate(xGnorm = (`xG+/-`-min(`xG+/-`))/(max(`xG+/-`)-min(`xG+/-`))) %>% 
  select(Player,`xG+/-`,xGnorm,`CFbin`,`CF%`) %>% 
  mutate(Player = fct_reorder(Player,xGnorm)) %>% 
  ggplot(aes(Player,xGnorm, size = `CFbin`, color= CFbin)) +
  geom_point()+
  coord_flip()
```


```{r}
leafs %>% 
  filter(GP.x>5) %>%
  select(Player,`P.x`, `CAP HIT`,`P/60`,`CF%`,`xG+/-`) %>% 
  mutate(`CAP HIT` = `CAP HIT`/1000000) %>% 
  ggplot(aes(`CAP HIT`,`P/60`))+
  geom_point()+
  labs(title = "Most productive Leaf contracts",
subtitle = "Comparing P/60 to Cap Hit") +
labs(x = "Cap Hit (in millions $)", y = "P60")+
  geom_text_repel(aes(`CAP HIT`, `P/60`, label = Player), size = 3)+
  theme_economist() + scale_fill_economist() +
theme(axis.line.x = element_line(size = .5, colour = "black"),
axis.title = element_text(size = 12),
legend.position = "bottom", legend.direction = "horizontal",
legend.text = element_text(size = 10),
plot.title = element_text(family = "Roboto Condensed"),
text = element_text(family = "Roboto Condensed"))
```

#calculate league rates for 2019
```{r}
NHL[is.na(NHL)] <- 0

NHL %>% 
  filter(Season == "2019",
         GP>8,
         Position == "C" | Position =="R" | Position =="L") %>% 
  mutate(Pointpercent = (P/sum(P)*100)) %>% 
  select(Player,Pointpercent,Position,P) %>% 
  arrange(desc(Pointpercent)) %>% 
  mutate(rank = row_number()) %>% 
  group_by(Position) %>% 
  mutate(Pointbin = cut(`rank`, c(0,93,186,279,372,Inf), labels = c("1st line","2nd line","3rd line","4th line","extra"))) %>% 
  filter(Player == "Kasperi Kapanen" | Player == "Andreas Johnsson" | Player == "Tyler Ennis")

NHL %>% 
  filter(Season == "2019",
         GP>8,
         Position == "C" | Position =="R" | Position =="L") %>% 
  select(Player,Position,P,`P/60`) %>% 
  arrange(desc(`P/60`)) %>% 
  mutate(rank = row_number()) %>% 
  group_by(Position) %>% 
  mutate(Pointbin = cut(`rank`, c(0,93,186,279,372,Inf), labels = c("1st line","2nd line","3rd line","4th line","extra"))) %>% 
  filter(Player == "Kasperi Kapanen" | Player == "Andreas Johnsson" | Player == "Tyler Ennis")


```

```{r}
#Ennis

fill <- c("#00a3dc","#01526d")

NHL %>% 
  filter(Player == "Tyler Ennis") %>% 
  ggplot(aes(Season,`P/60`)) +
geom_col() +
geom_text(aes(label = `P/60`), position = position_stack(vjust = 0.5),
colour = "white", size = 3, family = "Roboto Condensed",
show.legend = F) +
scale_x_continuous(breaks = seq(2008,2019,1)) +
labs(title = "Tyler Ennis P/60",
subtitle = "By year") +
labs(x = "Year", y = "P/60") +
  theme_economist() + scale_fill_manual(values = fill) +
theme(axis.line.x = element_line(size = .5, colour = "black"),
legend.position = "bottom", legend.direction = "horizontal",
legend.title = element_blank(),
plot.title = element_text(family = "Roboto Condensed"),
text = element_text(family = "Roboto Condensed")) +
guides(fill = guide_legend(reverse = T))

```

```{r}
#Kapanen
NHL %>% 
  filter(Season == 2019) %>% 
  mutate(`meanP/60` = mean(`P/60`)) %>% 
  select(Player, `P/60`, `meanP/60`) %>% 
  filter(Player == "Kasperi Kapanen")

NHL %>% 
  filter(Season == 2019) %>% 
    mutate(Player = if_else(Player == "Kasperi Kapanen", "Kasperi Kapanen",
                                                         "League Average")) %>% group_by(Player) %>% 
  summarize(P = mean(P)) %>% 
  mutate(P=round(P)) %>% 
  ggplot(aes(Player,`P`)) +
geom_col() +
geom_text(aes(label = `P`), position = position_stack(vjust = 0.5),
colour = "white", size = 5, family = "Roboto Condensed",
show.legend = F) +
labs(title = "Kapanen 5v5 Points") +
labs(x = "Player", y = "Points") +
  theme_economist() + scale_fill_manual(values = fill) +
theme(axis.line.x = element_line(size = .5, colour = "black"),
legend.position = "bottom", legend.direction = "horizontal",
legend.title = element_blank(),
plot.title = element_text(family = "Roboto Condensed"),
text = element_text(family = "Roboto Condensed")) +
guides(fill = guide_legend(reverse = T))

NHL %>% 
  filter(Season == 2019) %>% 
    mutate(Player = if_else(Player == "Kasperi Kapanen", "Kasperi Kapanen",
                                                         "League Average")) %>% group_by(Player) %>% 
  summarize(`P/60` = mean(`P/60`)) %>% 
  mutate(`P/60`=round(`P/60`,2)) %>% 
  ggplot(aes(Player,`P/60`)) +
geom_col() +
geom_text(aes(label = `P/60`), position = position_stack(vjust = 0.5),
colour = "white", size = 5, family = "Roboto Condensed",
show.legend = F) +
labs(title = "Kapanen 5v5 Points per 60") +
labs(x = "Player", y = "Points") +
  theme_economist() + scale_fill_manual(values = fill) +
theme(axis.line.x = element_line(size = .5, colour = "black"),
legend.position = "bottom", legend.direction = "horizontal",
legend.title = element_blank(),
plot.title = element_text(family = "Roboto Condensed"),
text = element_text(family = "Roboto Condensed")) +
guides(fill = guide_legend(reverse = T))


```

```{r}
#Johnnson
NHL %>% 
  filter(Season == 2019) %>% 
    mutate(Player = if_else(Player == "Andreas Johnsson", "Andreas Johnsson",
                                                         "League Average")) %>% group_by(Player) %>% 
  summarize(P = mean(P)) %>% 
  mutate(P=round(P)) %>% 
  ggplot(aes(Player,`P`)) +
geom_col() +
geom_text(aes(label = `P`), position = position_stack(vjust = 0.5),
colour = "white", size = 5, family = "Roboto Condensed",
show.legend = F) +
labs(title = "Johnsson 5v5 Points") +
labs(x = "Player", y = "Points") +
  theme_economist() + scale_fill_manual(values = fill) +
theme(axis.line.x = element_line(size = .5, colour = "black"),
legend.position = "bottom", legend.direction = "horizontal",
legend.title = element_blank(),
plot.title = element_text(family = "Roboto Condensed"),
text = element_text(family = "Roboto Condensed")) +
guides(fill = guide_legend(reverse = T))

NHL %>% 
  filter(Season == 2019) %>% 
    mutate(Player = if_else(Player == "Andreas Johnsson", "Andreas Johnsson",
                                                         "League Average")) %>% group_by(Player) %>% 
  summarize(`P/60` = mean(`P/60`)) %>% 
  mutate(`P/60`=round(`P/60`,2)) %>% 
  ggplot(aes(Player,`P/60`)) +
geom_col() +
geom_text(aes(label = `P/60`), position = position_stack(vjust = 0.5),
colour = "white", size = 5, family = "Roboto Condensed",
show.legend = F) +
labs(title = "Johnsson 5v5 Points per 60") +
labs(x = "Player", y = "Points") +
  theme_economist() + scale_fill_manual(values = fill) +
theme(axis.line.x = element_line(size = .5, colour = "black"),
legend.position = "bottom", legend.direction = "horizontal",
legend.title = element_blank(),
plot.title = element_text(family = "Roboto Condensed"),
text = element_text(family = "Roboto Condensed")) +
guides(fill = guide_legend(reverse = T))
```

