---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(viridis)
library(awtools)

library(showtext)
library(extrafont)
library(lubridate)

font_add_google("IBM Plex Mono", "IBM Plex Mono")
font_add_google("IBM Plex Sans", "IBM Plex Sans")

showtext_auto()
```

```{r}
LTrbrUQc-7ppNQ
cVC_whdKJq520J51BEfzD6h5MoU
```

```{r}
reddit = read_csv('leafsreddit.csv')
```
```{r}
reddit %>% 
  mutate(date = as.Date(timestamp)) %>% 
  filter(date>'2019-12-31') %>% 
  head(10) %>% 
  mutate(title = str_wrap(title, width = 80)) %>% 
  ggplot(aes(reorder(title,score),score)) +
  geom_col(fill = '#00205b') +
  coord_flip() +
  a_plex_theme(grid = FALSE) +
  geom_text(aes(label = score), hjust = -0.17, color = '#00205b') +
  ylim(0,3800) +
  labs(caption = "Chart by @MackinawStats", x = "")

ggsave('leafsreddit2.pdf', height = 10, width = 10)
```

