---
title: "beeswarm"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(fuzzyjoin)
library(stringr)
library(ggthemes)
library(ggrepel)
library(extrafont)
library(hrbrthemes)
library(xkcd)
library(cowplot)
library(magick)
library(zoo)
library(gganimate)
library(ggimage)
library(beeswarm)
library(ggbeeswarm)

shots = read_csv("all_teams.csv")
  
fivexg = shots %>% 
  filter(situation == "5on5") %>% 
  group_by(season, team) %>% 
  summarize(avgxG = mean(xGoalsPercentage)) %>%
  mutate(avgxG = round(avgxG*100,2))
```

```{r}

team = filter(fivexg, team == "TOR")

fivexg %>%
  ggplot(aes(season,avgxG)) +
  geom_quasirandom(dodge.width = 1, alpha = 0.1) +
  geom_point(data = team, color = "#003E7E", size = 2, alpha = 1) +
  geom_line(data = team, alpha = 0.5, linetype = 'dashed') +
  scale_x_continuous(breaks=c(2008:2018)) +
  theme_fivethirtyeight() +
  labs(x = "Season", y="Expected Goals Percentage", title = "Expected Goals Percentage since 2008", subtitle = "Data from Moneypuck.com")
```

```{r}
fivecf = shots %>% 
  filter(situation == "5on5") %>% 
  group_by(season, team) %>% 
  summarize(avgcf = mean(corsiPercentage)) %>%
  mutate(avgcf = round(avgcf*100,2))

team = filter(fivecf, team == "TOR")

fivecf %>%
  ggplot(aes(season,avgcf)) +
  geom_quasirandom(dodge.width = 1, alpha = 0.1) +
  geom_point(data = team, color = "#003E7E", size = 2, alpha = 1) +
  geom_line(data = team, alpha = 0.5, linetype = 'dashed') +
  scale_x_continuous(breaks=c(2008:2018)) +
  theme_fivethirtyeight() +
  labs(x = "Season", y="Corsi Percentage", title = "Corsi Percentage since 2008", subtitle = "Data from Moneypuck.com")
```

