---
title: "marleau"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(here)
library(fuzzyjoin)
library(stringr)
library(ggthemes)
library(ggrepel)
library(extrafont)
library(hrbrthemes)
library(xkcd)
library(cowplot)
library(magick)
library(zoo)
library(gganimate)
library(ggimage)
library(beeswarm)
library(ggbeeswarm)
library(plotly)

rapm = read_csv(here("RAPM.csv"))
```
```{r}
player = filter(rapm, player == "PATRICK.MARLEAU")

rapm %>% 
  ggplot(aes(season, `xGPM_60`)) +
  geom_quasirandom(dodge.width = 1, alpha = 0.1) +
   geom_point(data = player, color = "#003E7E", size = 2, alpha = 1) +
  geom_line(data = player, alpha = 0.5, linetype = 'dashed') + 
  scale_x_continuous(breaks = c(20132014, 20142015, 20152016, 20162017, 20172018, 20182019)) +
  theme_fivethirtyeight() +
  labs(title = "Patrick Marleau's decline", subtitle = "5v5 Expected Goals Plus/Minus Per 60")
```

```{r}
rapm %>% 
  ggplot(aes(season, `GPM_60`)) +
  geom_quasirandom(dodge.width = 1, alpha = 0.1) +
   geom_point(data = player, color = "#003E7E", size = 2, alpha = 1) +
  geom_line(data = player, alpha = 0.5, linetype = 'dashed') + 
  scale_x_continuous(breaks = c(20132014, 20142015, 20152016, 20162017, 20172018, 20182019)) +
  theme_fivethirtyeight() +
  labs(title = "Patrick Marleau's decline", subtitle = "5v5 Goals Plus/Minus Per 60")
```

```{r}
rapm %>% 
  ggplot(aes(season, `CPM_60`)) +
  geom_quasirandom(dodge.width = 1, alpha = 0.1) +
   geom_point(data = player, color = "#003E7E", size = 2, alpha = 1) +
  geom_line(data = player, alpha = 0.5, linetype = 'dashed') + 
  scale_x_continuous(breaks = c(20132014, 20142015, 20152016, 20162017, 20172018, 20182019)) +
  theme_fivethirtyeight() +
  labs(title = "Patrick Marleau's decline", subtitle = "Corsi Plus/Minus Per 60")
```



team = filter(five, team == "TOR")

five %>%
  ggplot(aes(season,avgxG)) +
  geom_quasirandom(dodge.width = 1, alpha = 0.1) +
  geom_point(data = team, color = "#003E7E", size = 2, alpha = 1) +
  geom_line(data = team, alpha = 0.5, linetype = 'dashed') +
  scale_x_continuous(breaks=c(2008:2018)) +
  theme_fivethirtyeight() +
  labs(x = "Season", y="Expected Goals Percentage", title = "Expected Goals Percentage since 2008", subtitle = "Data from Moneypuck.com")