---
title: "player charts"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(fuzzyjoin)
library(stringr)
library(ggthemes)
library(ggrepel)
library(extrafont)
library(hrbrthemes)
library(xkcd)
library(cowplot)
library(magick)
library(zoo)
library(gganimate)
library(ggimage)
library(beeswarm)
library(DescTools)
library(ggbeeswarm)
library(plotly)
library(awtools)
library(showtext)
library(ggforce)
library(ggridges)
library(tidytext)
library(rayshader)
library(rgl)
library(ggpointdensity)
library(viridis)

nhl = read_csv("shots_2018.csv") %>% 
  mutate(teamCode = case_when(shooterName == "Alexander Kerfoot" ~ "TOR", TRUE ~ teamCode)) %>% 
  mutate(arenaAdjustedXCord = case_when(teamCode == "TOR" ~ abs(arenaAdjustedXCord),
                                        teamCode == "MTL" ~ -abs(arenaAdjustedXCord),
                                        TRUE ~ arenaAdjustedXCord)) %>% 
  mutate(arenaAdjustedYCord = arenaAdjustedYCord * -1) %>% 
  mutate(totalplayersshootingteam = shootingTeamDefencemenOnIce + shootingTeamForwardsOnIce,
         totalplayersdefendingteam = defendingTeamDefencemenOnIce + defendingTeamForwardsOnIce) %>% 
  mutate(pp = case_when(totalplayersshootingteam>totalplayersdefendingteam~ "PP", TRUE ~ "0"))
  
```

```{r}
gg_rink <- function(side = "right", specs = "nhl"){
  
  ### this function uses ggplot's annotate()
  # to draw the rink.
  # I recommend calling this function PRIOR to invoking
  # geoms for data so that the points aren't covered
  # by the annotations
  
  ### inputs:
  #     1. side = which side to plot: "right" (default) or "left"
  #     2. specs = which rink size to use: "nhl" (default) or "iihf" for
  #        international
  
  # check inputs
  side <- tolower(side)
  specs <- tolower(specs)
  stopifnot(side %in% c("right", "left"))
  stopifnot(specs %in% c("nhl", "iihf"))
  
  side <- switch(side,
                 "right" = 1,
                 "left" = -1)
  
  nsteps <- 1001 # line resolution for drawing circles/segments
  circle <- seq(0, 2*pi, length = nsteps) # angles to draw a circle
  
  switch(specs,
         "nhl" = {
           # NHL specifications
           # all units in feet
           
           ### rink boundaries ###
           ## assumed to be standard 200x85ft dimensions
           x_max <- 100
           y_max <- 42.5
           y_min <- -y_max
           # blue line 75' from end boards
           x_blue <- x_max - 75
           # goal line 11' from end boards
           x_goal <- x_max - 11
           
           ### parameter setup
           ## corners rounded in arc of circle with 28' radius
           r_corner <- 28
           
           ## crease semi-circle
           # 6' radius from center of goal line starting 4.5' out
           crease_end <- 4.5
           r_crease <- 6
           # deepest point of net is 40"
           net_depth <- 40/12
           # crease is 8' long; goal posts 6' apart
           goal_post_start <- 6/2
           crease_start_y <- 8/2
           # inner crease lines begin 4' from goal line
           # extend 5" into crease
           crease_small_start <- 4
           crease_small_length <- 5/12
           
           ## face-off circle dots and lines
           # dot locations: 20' from goal line, 22' in each y direction
           x_dot_dist <- 20
           y_faceoff_dot <- 22
           # face-off circle radius 15'
           r_faceoff <- 15
           # hash marks 2' long, 5'7" apart
           hash_length <- 2
           hash_space <- 67/12
           # circle inner lines:
           # x-direction: lines 4' apart, so start 2' from dot
           # y-direction: lines 18" apart, so start 9" from dot
           inner_start_x <- 2
           inner_start_y <- 1.5/2
           # lines parallel to side boards: 4' long
           par_side_length <- 4
           # lines parallel to end boards: 3' long
           par_end_length <- 3
           
           ## other parameters
           # neutral zone dots are 5' from blue line, 44' apart
           x_dot_neutral <- 5
           # ref circle 5m radius
           r_ref <- 5
           ## trapezoid (NHL only)
           # begins 8' from each goal post
           # bottom base is 28' long
           y_traps_start <- goal_post_start + 8
           y_traps_end <- 14
         },
         "iihf" = {
           # IIHF specifications
           # all units in meters
           
           ### rink boundaries ###
           ## assumed to be standard 60x30m dimensions
           x_max <- 30
           y_max <- 15
           y_min <- -y_max
           # blue line 22.86m from end boards, 30cm wide
           x_blue <- x_max - 22.86
           # goal line 4m from end boards
           x_goal <- x_max - 4
           
           ### parameter setup
           ## corners rounded in arc of circle with 8.5m radius
           r_corner <- 8.5
           
           ## crease semi-circle
           # 183cm radius from center of goal line starting 137cm out
           crease_end <- 1.37
           r_crease <- 1.83
           # deepest point of net is 1.12m
           net_depth <- 1.12
           # crease is 244cm long; goal posts 183.5cm apart
           goal_post_start <- 1.835/2
           crease_start_y <- 2.44/2
           # inner crease lines begin 122cm from goal line
           # extend 13m into crease
           crease_small_start <- 1.22
           crease_small_length <- 0.13
           
           ## face-off circle dots and lines
           # dot locations: 6m from goal line, 7m in each y direction
           x_dot_dist <- 6
           y_faceoff_dot <- 7
           # face-off circle radius 4.5m
           r_faceoff <- 4.5
           # hash marks 60cm long, 170cm apart
           hash_length <- 0.6
           hash_space <- 1.7
           # circle inner lines:
           # x-direction: lines 120cm apart, start 60cm from dot
           # y-direction: lines 45cm apart, so start 22.5cm from dot
           inner_start_x <- 0.6
           inner_start_y <- 0.225
           # lines parallel to side boards: 120cm long
           par_side_length <- 1.2
           # lines parallel to end boards: 90cm long
           par_end_length <- 0.9
           
           ## other parameters
           # neutral zone dots are 1.5m from blue line
           x_dot_neutral <- 1.5
           # ref circle 3m radius
           r_ref <- 3
         }
  )
  
  ## corners
  curve_angle <- seq(pi/2, 0, length = nsteps)
  curve_angle_last <- curve_angle[nsteps]
  # y coord at end of curve to connect ends
  y_curve_end <- (y_max - r_corner) + r_corner*sin(curve_angle_last)
  # for goal line, find y coord when x is at goal line
  goal_angle <- acos(
    (x_goal - (x_max - r_corner))/r_corner
  )
  y_goal <- (y_max - r_corner) + r_corner*sin(goal_angle)
  
  ## crease
  crease_angles <- seq(
    pi - acos(crease_end/r_crease),
    pi + acos(crease_end/r_crease),
    length = nsteps
  )
  
  ## face-off circle
  x_faceoff_dot <- x_goal - x_dot_dist
  # find y coord on circle where hashes begin
  y_hash <- r_faceoff*sin(
    acos((hash_space/2)/r_faceoff)
  )
  
  ### create list of components to pass to ggplot
  list(
    theme_minimal(),
    theme(panel.grid = element_blank()),
    ### blue line
    annotate(
      "segment",
      x = x_blue*side, y = y_max,
      xend = x_blue*side, yend = y_min,
      color = "blue", size = 2
    ),
    ### ref crease
    annotate(
      "path",
      x = r_ref*cos(seq(pi/2, 0, length = nsteps))*side,
      y = y_min + r_ref*sin(seq(pi/2, 0, length = nsteps)),
      color = "red"
    ),
    ### face-off circle, center ice
    annotate(
      "path",
      x = r_faceoff*cos(seq(pi/2, -pi/2, length = nsteps))*side,
      y = r_faceoff*sin(seq(pi/2, -pi/2, length = nsteps)),
      color = "blue"
    ),
    ### center line:
    annotate(
      "segment",
      x = 0, y = y_max,
      xend = 0, yend = y_min,
      color = "red", size = 2
    ),
    switch(specs,
           "nhl" = annotate(
             # dashed white lines atop center line (NHL only)
             "segment",
             x = 0, y = y_max,
             xend = 0, yend = y_min,
             color = "white", size = 0.5, linetype = "dashed"
           ),
           "iihf" = annotate(
             # 50cm space between lines around center dot
             "segment",
             x = 0, y = 0.5,
             xend = 0, yend = -0.5,
             color = "white", size = 2.5
           )
    ),
    ### face-off dot, center ice
    annotate(
      "point",
      x = 0,
      y = 0,
      color = "blue", size = 1
    ),
    ### neutral zone dots
    annotate(
      "point",
      x = (x_blue - x_dot_neutral)*side,
      y = y_faceoff_dot*c(1, -1),
      color = "red", size = 1
    ),
    ### side boards
    annotate(
      "segment",
      x = 0, y = c(y_min, y_max),
      # stop where corner curve begins
      xend = (x_max - r_corner)*side, yend = c(y_min, y_max),
      size = 1
    ),
    ### ends
    # goal line
    annotate(
      "segment",
      x = x_goal*side, y = y_goal,
      xend = x_goal*side, yend = -y_goal,
      color = "red"
    ),
    # connect ends
    annotate(
      "segment",
      x = x_max*side, y = y_curve_end,
      xend = x_max*side, yend = -y_curve_end,
      size = 1
    ),
    # corners rounded in arc of circle
    # starting point: (x_max, y_max) - r_circle from pi/2 to 0
    annotate(
      "path",
      x = ((x_max - r_corner) + r_corner*cos(curve_angle))*side,
      y = (y_max - r_corner) + r_corner*sin(curve_angle),
      size = 1
    ),
    annotate(
      "path",
      x = ((x_max - r_corner) + r_corner*cos(curve_angle))*side,
      y = -((y_max - r_corner) + r_corner*sin(curve_angle)),
      size = 1
    ),
    ### crease
    annotate(
      "segment",
      x = x_goal*side,
      y = crease_start_y*c(-1, 1),
      xend = (x_goal - crease_end)*side,
      yend = crease_start_y*c(-1, 1),
      col = "red"
    ),
    # crease lines
    annotate(
      "segment",
      x = (x_goal - crease_small_start)*side,
      y = crease_start_y*c(-1, 1),
      xend = (x_goal - crease_small_start)*side,
      yend = (crease_start_y - crease_small_length)*c(-1, 1),
      col = "red"
    ),
    # semi-circle starting 137cm out with 183cm radius from center of goal line
    annotate(
      "path",
      x = (x_goal + r_crease*cos(crease_angles))*side,
      y = r_crease*sin(crease_angles),
      col = "red"
    ),
    if (specs == "nhl") {
      ### restricted area (NHL only)
      annotate(
        "segment",
        x = x_goal*side, y = y_traps_start*c(-1, 1),
        xend = x_max*side, yend = y_traps_end*c(-1, 1),
        color = "red"
      )
    },
    ### net
    annotate(
      "segment",
      x = x_goal*side,
      y = goal_post_start*c(-1, 1),
      xend = (x_goal + net_depth)*side,
      yend = goal_post_start*c(-1, 1)
    ),
    annotate(
      "segment",
      x = (x_goal + net_depth)*side,
      y = -goal_post_start,
      xend = (x_goal + net_depth)*side,
      yend = goal_post_start
    ),
    ### face-off circles
    # dot
    annotate(
      "point",
      x = x_faceoff_dot*side,
      y = y_faceoff_dot*c(1, -1),
      col = "red",
      size = 1
    ),
    # circles 
    annotate(
      # top
      "path",
      x = side*(x_faceoff_dot + r_faceoff*cos(circle)),
      y = y_faceoff_dot + r_faceoff*sin(circle),
      col = "red"
    ),
    annotate(
      # bottom
      "path",
      x = side*(x_faceoff_dot + r_faceoff*cos(circle)),
      y = -(y_faceoff_dot + r_faceoff*sin(circle)),
      col = "red"
    ),
    # hashes
    annotate(
      "segment",
      x = side*(
        x_faceoff_dot + (hash_space/2)*rep(c(1, -1), each = 4)
      ),
      y = (y_faceoff_dot + y_hash*c(1, -1))*rep(c(1, 1, -1, -1), times = 2),
      xend = side*(
        x_faceoff_dot + (hash_space/2)*rep(c(1, -1), each = 4)
      ),
      yend = (y_faceoff_dot + (y_hash + hash_length)*c(1, -1))*
        rep(c(1, 1, -1, -1), times = 2),
      col = "red"
    ),
    ## inner lines
    # parallel to side boards
    annotate(
      # parallel to side boards
      "segment",
      x = side*(
        x_faceoff_dot + inner_start_x*rep(c(1, -1), each = 4)
      ),
      y = (y_faceoff_dot + inner_start_y*c(1, -1))*
        rep(c(1, 1, -1, -1), times = 2),
      xend = side*(
        x_faceoff_dot + (inner_start_x + par_side_length)*
          rep(c(1, -1), each = 4)
      ),
      yend = (y_faceoff_dot + inner_start_y*c(1, -1))*
        rep(c(1, 1, -1, -1), times = 2),
      col = "red"
    ),
    annotate(
      # parallel to end boards
      "segment",
      x = side*(
        x_faceoff_dot + inner_start_x*rep(c(1, -1), each = 4)
      ),
      y = (y_faceoff_dot + inner_start_y*c(1, -1))*
        rep(c(1, 1, -1, -1), times = 2),
      xend = side*(
        x_faceoff_dot + inner_start_x*rep(c(1, -1), each = 4)
      ),
      yend = (y_faceoff_dot + (inner_start_y + par_end_length)*c(1, -1))*
        rep(c(1, 1, -1, -1), times = 2),
      col = "red"
    )
  )
}
```

```{r}
matthews = nhl %>% 
  filter(shooterName == "Auston Matthews", event == "GOAL") %>% 
  mutate(goalnum = row_number())

anim = matthews %>% 
   ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord, size =xGoal)) +
  geom_point(aes(color = pp), alpha = 0.6) +
  gg_rink(side = "right") +
  labs(title = "Auston Matthews Goal Locations", subtitle = "Data from Moneypuck.com", x = "", y = "") +
  scale_color_manual(values = c("#00205B", "orange")) +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) + 
  scale_size_continuous(name="area", range = c(1,12)) +
  transition_states(goalnum) +
  shadow_mark()

animate(anim, end_pause = 30, rewind = FALSE)

anim_save("matthews.gif")
```
```{r}
matthews %>% 
   ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord, size =xGoal)) +
  geom_point(aes(color = pp), alpha = 0.6) +
  gg_rink(side = "right") +
  labs(title = "Auston Matthews Goal Locations", subtitle = "Data from Moneypuck.com", x = "", y = "") +
  scale_color_manual(values = c("#00205B", "orange")) +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) + 
  scale_size_continuous(name="area", range = c(1,10)) +
  transition_states(goalnum) +
  shadow_mark()
```
```{r}
line1 = nhl %>% 
  filter(shooterName == "John Tavares" | shooterName == "Mitchell Marner" | shooterName == "Zach Hyman", event == "GOAL") %>% 
  mutate(goalnum = row_number())

line1 = line1 %>% 
   ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord, size =xGoal)) +
  geom_point(aes(color = pp), alpha = 0.6) +
  gg_rink(side = "right") +
  labs(title = "Tavares Line Goal Locations", subtitle = "Data from Moneypuck.com", x = "", y = "") +
  scale_color_manual(values = c("#00205B", "orange")) +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) + 
  scale_size_continuous(name="area", range = c(1,10)) +
  facet_wrap(~shooterName) +
  transition_states(goalnum) +
  shadow_mark()

animate(line1, end_pause = 30, rewind = FALSE, width = 1200)

anim_save("line1.gif")
```
```{r}
nhl %>% 
  filter(teamCode == "TOR") %>% 
  filter(playerPositionThatDidEvent == "C" | playerPositionThatDidEvent == "L" | playerPositionThatDidEvent == "R") %>% 
  group_by(shooterName, game_id) %>% 
  summarize(xGoal = sum(xGoal)) %>% 
  select(-game_id) %>% 
  ungroup() %>% 
  mutate(shooterName = fct_reorder(shooterName, xGoal)) %>% 
  ggplot(aes(x = xGoal, y = shooterName, fill = ..x..)) +
  geom_density_ridges_gradient(rel_min_height = 0.01, alpha = 0.2, jittered_points = TRUE) +
  scale_fill_viridis(option = "C") +
  labs(title = "Leafs' Expected Goals Game Distributions", subtitle = "Ordered by Median Expected Goals Per Game, Data from MoneyPuck", x = "Expected Goals (Per Game Basis)", y = "") +
  theme_ipsum_rc(grid = FALSE) +
  theme(legend.position = "none")

ggsave("leafsridges.png")
  
```

```{r}
nhl %>% 
  filter(teamCode == "TOR") %>% 
  filter(playerPositionThatDidEvent == "C" | playerPositionThatDidEvent == "L" | playerPositionThatDidEvent == "R") %>% 
  group_by(shooterName, game_id) %>% 
  summarize(xGoal = sum(xGoal)) %>% 
  select(-game_id) %>% 
  ungroup() %>% 
  mutate(shooterName = fct_reorder(shooterName, xGoal, .fun = mean)) %>% 
  ggplot(aes(x = xGoal, y = shooterName, fill = ..x..)) +
  geom_density_ridges_gradient(rel_min_height = 0.01, alpha = 0.2, jittered_points = TRUE) +
  scale_fill_viridis(option = "C") +
  labs(title = "Leafs' Expected Goals Game Distributions", subtitle = "Ordered by Median Expected Goals Per Game, Data from MoneyPuck", x = "Expected Goals (Per Game Basis)", y = "") +
  theme_ipsum_rc(grid = FALSE) +
  theme(legend.position = "none") +
  geom_vline(xintercept = 0.2)
```

```{r}
nhl %>% 
  filter(shooterName == "Auston Matthews") %>% 
  ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord)) +
  stat_density2d(aes(fill = ..level..), geom = 'polygon') +
  scale_fill_viridis() +
  gg_rink(side = "right") +
  labs(title = "Auston Matthews Shot Locations", subtitle = "Data from Moneypuck.com", x = "", y = "") +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

ggsave("matthewskernal.png")
```

```{r}
nhl %>% 
  filter(shooterName == "Alexander Kerfoot") %>% 
  ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord)) +
  stat_density2d(aes(fill = ..level..), geom = 'polygon') +
  scale_fill_viridis() +
  geom_point(alpha = 0.2) +
  gg_rink(side = "right") +
  labs(title = "Alexander Kerfoot Shot Locations", subtitle = "Data from Moneypuck.com", x = "", y = "") +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```

```{r}
nhl %>% 
  filter(shooterName == "Mitchell Marner") %>% 
  ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord)) +
  stat_density2d(aes(fill = ..level..), geom = 'polygon') +
  scale_fill_viridis() +
  geom_point(alpha = 0.2) +
  gg_rink(side = "right") +
  labs(title = "Alexander Kerfoot Shot Locations", subtitle = "Data from Moneypuck.com", x = "", y = "") +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```

```{r}
sens = read_csv("shots_2019_1003.csv") %>% 
  filter(game_id == 20001) %>% 
  mutate(arenaAdjustedXCord = case_when(teamCode == "TOR" ~ abs(arenaAdjustedXCord),
                                        teamCode == "OTT" ~ -abs(arenaAdjustedXCord),
                                        TRUE ~ arenaAdjustedXCord)) %>% 
  mutate(arenaAdjustedYCord = arenaAdjustedYCord * -1)

jackets = read_csv("shots_2019_1003.csv") %>% 
  filter(game_id == 20015) %>% 
  mutate(arenaAdjustedXCord = case_when(teamCode == "TOR" ~ abs(arenaAdjustedXCord),
                                        teamCode == "CBJ" ~ -abs(arenaAdjustedXCord),
                                        TRUE ~ arenaAdjustedXCord)) %>% 
  mutate(arenaAdjustedYCord = arenaAdjustedYCord * -1)
```

```{r}
sens %>% 
  ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord)) +
  stat_density2d(aes(fill = ..level..), geom = 'polygon') +
  scale_fill_viridis() +
  geom_point(alpha = 0.2) +
  gg_rink(side = "right") +
  gg_rink(side = "left") +
  labs(title = "Alexander Kerfoot Shot Locations", subtitle = "Data from Moneypuck.com", x = "", y = "") +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```

  
```{r}
sens %>% 
  ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord)) +
  geom_point(size = 4,aes(color = teamCode)) +
  gg_rink(side = "right") +
  gg_rink(side = "left") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```
```{r}
font_add_google("IBM Plex Mono", "IBM Plex Mono")
font_add_google("IBM Plex Sans", "IBM Plex Sans")

showtext_auto()

sens %>% 
  ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord)) +
  geom_point() +
  stat_density2d(aes(fill = ..level..), geom = 'polygon', h =17) +
  scale_fill_viridis() +
  gg_rink(side = "right") +
  gg_rink(side = "left") +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(title = "TOR Vs. OTT, Shots Heatmap", subtitle = "Data from Moneypuck", caption = "Chart by @MackinawStats")

ggsave("heatmap1003.pdf")
```
```{r}
font_add_google("IBM Plex Mono", "IBM Plex Mono")
font_add_google("IBM Plex Sans", "IBM Plex Sans")

showtext_auto()

jackets %>% 
  ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord)) +
  geom_point() +
  stat_density2d(aes(fill = ..level..), geom = 'polygon', h =17) +
  scale_fill_viridis() +
  gg_rink(side = "right") +
  gg_rink(side = "left") +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(title = "TOR Vs. CBJ, Shots Heatmap", subtitle = "Data from Moneypuck", caption = "Chart by @MackinawStats")

ggsave("heatmap1004.pdf")
```

```{r}
library(downloader)
download("http://peter-tanner.com/moneypuck/downloads/shots_2019.zip", dest="dataset.zip", mode="wb") 
unzip ("dataset.zip", exdir = "C:\\Users\\rghizzoni\\Documents\\NHL")
shots = read_csv("shots_2019.csv")
```
```{r}
mtl = shots %>% 
  filter(game_id == 20019) %>% 
  mutate(arenaAdjustedXCord = case_when(teamCode == "TOR" ~ abs(arenaAdjustedXCord),
                                        teamCode != "TOR" ~ -abs(arenaAdjustedXCord),
                                        TRUE ~ arenaAdjustedXCord)) %>% 
  mutate(arenaAdjustedYCord = arenaAdjustedYCord * -1)
```

```{r}
font_add_google("IBM Plex Mono", "IBM Plex Mono")
font_add_google("IBM Plex Sans", "IBM Plex Sans")

showtext_auto()

mtl %>% 
  ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord)) +
  geom_point() +
  stat_density2d(aes(fill = ..level..), geom = 'polygon', h =17) +
  scale_fill_viridis(option = "plasma") +
  gg_rink(side = "right") +
  gg_rink(side = "left") +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(title = "TOR Vs. MTL, Shots Heatmap", subtitle = "Data from Moneypuck", caption = "Chart by @MackinawStats")

ggsave("heatmap1006.pdf")
```
```{r}
games = c("20001","20015","20019")

```

```{r}
shots %>% 
  mutate(game = case_when(game_id == "20001" ~ 1,
                          game_id == "20015" ~ 2,
                          game_id == "20019" ~ 3)) %>% 
  filter(game_id %in% games) %>% 
  mutate(arenaAdjustedXCord = case_when(teamCode == "TOR" ~ abs(arenaAdjustedXCord),
                                        teamCode != "TOR" ~ -abs(arenaAdjustedXCord),
                                        TRUE ~ arenaAdjustedXCord)) %>%
  mutate(arenaAdjustedYCord = arenaAdjustedYCord * -1) %>% 
   ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord)) +
  stat_density2d(aes(fill = ..level..), geom = 'polygon', h =17) +
  scale_fill_viridis(option = "plasma") +
  gg_rink(side = "right") +
  gg_rink(side = "left") +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(title = "TOR Vs. MTL, Shots Heatmap", subtitle = "Data from Moneypuck", caption = "Chart by @MackinawStats") +
  facet_wrap(~game_id, ncol = 1)

graph2ppt(file="plots.pptx", width=4, height=8, append=TRUE)
```

```{r}
stl = shots %>% 
  filter(game_id == 20034) %>% 
  mutate(arenaAdjustedXCord = case_when(teamCode == "TOR" ~ abs(arenaAdjustedXCord),
                                        teamCode != "TOR" ~ -abs(arenaAdjustedXCord),
                                        TRUE ~ arenaAdjustedXCord)) %>% 
  mutate(arenaAdjustedYCord = arenaAdjustedYCord * -1)

stl %>% 
  ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord)) +
  geom_point() +
  stat_density2d(aes(fill = ..level..), geom = 'polygon', h =17) +
  scale_fill_viridis(option = "plasma") +
  gg_rink(side = "right") +
  gg_rink(side = "left") +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(title = "TOR Vs. STL, Shots Heatmap", subtitle = "Data from Moneypuck", caption = "Chart by @MackinawStats")

ggsave("heatmap1008.pdf")
```

```{r}
tbl = shots %>% 
  filter(game_id == 20047) %>% 
  mutate(arenaAdjustedXCord = case_when(teamCode == "TOR" ~ abs(arenaAdjustedXCord),
                                        teamCode != "TOR" ~ -abs(arenaAdjustedXCord),
                                        TRUE ~ arenaAdjustedXCord)) %>% 
  mutate(arenaAdjustedYCord = arenaAdjustedYCord * -1)

tbl %>% 
  ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord)) +
  geom_point() +
  stat_density2d(aes(fill = ..level..), geom = 'polygon', h =17) +
  scale_fill_viridis(option = "plasma") +
  gg_rink(side = "right") +
  gg_rink(side = "left") +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(title = "TOR Vs. TBL, Shots Heatmap", subtitle = "Data from Moneypuck", caption = "Chart by @MackinawStats")

ggsave("heatmap1010.pdf")
```

```{r}
det = shots %>% 
  filter(game_id == 20066) %>% 
  mutate(arenaAdjustedXCord = case_when(teamCode == "TOR" ~ abs(arenaAdjustedXCord),
                                        teamCode != "TOR" ~ -abs(arenaAdjustedXCord),
                                        TRUE ~ arenaAdjustedXCord)) %>% 
  mutate(arenaAdjustedYCord = arenaAdjustedYCord * -1)

det %>% 
  ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord)) +
  stat_density2d(aes(fill = ..level..), geom = 'polygon', h =14) +
  scale_fill_viridis(option = "plasma") +
  gg_rink(side = "right") +
  gg_rink(side = "left") +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(title = "TOR Vs. DET, Shots Heatmap", subtitle = "Data from Moneypuck", caption = "Chart by @MackinawStats") +
  geom_point(color = "yellow", alpha = 0.2) +
  annotate(geom = "text",
           x = 30, y = 47, size = 4,
           label = "Toronto Shots For", hjust = 0, family = "IBM Plex Sans") +
  theme(legend.position = "none") +
  annotate(geom = "text",
           x = -80, y = 47, size = 4,
           label = "Detroit Shots For", hjust = 0, family = "IBM Plex Sans") +
  theme(legend.position = "none")

ggsave("heatmap1013.pdf")
```
```{r}
min = shots %>% 
  filter(game_id == 20085) %>% 
  mutate(arenaAdjustedXCord = case_when(teamCode == "TOR" ~ abs(arenaAdjustedXCord),
                                        teamCode != "TOR" ~ -abs(arenaAdjustedXCord),
                                        TRUE ~ arenaAdjustedXCord)) %>% 
  mutate(arenaAdjustedYCord = arenaAdjustedYCord * -1)

min %>% 
  ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord)) +
  stat_density2d(aes(fill = ..level..), geom = 'polygon', h =12) +
  scale_fill_viridis(option = "plasma") +
  gg_rink(side = "right") +
  gg_rink(side = "left") +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(title = "TOR Vs. MIN, Shots Heatmap", subtitle = "Data from Moneypuck", caption = "Chart by @MackinawStats") +
  geom_point(color = "yellow", alpha = 0.2) +
  annotate(geom = "text",
           x = 30, y = 47, size = 4,
           label = "Toronto Shots For", hjust = 0, family = "IBM Plex Sans") +
  theme(legend.position = "none") +
  annotate(geom = "text",
           x = -80, y = 47, size = 4,
           label = "Minnesota Shots For", hjust = 0, family = "IBM Plex Sans") +
  theme(legend.position = "none")

ggsave("heatmap1015.pdf")
```

```{r}
wsh = shots %>% 
  filter(game_id == 20093) %>% 
  mutate(arenaAdjustedXCord = case_when(teamCode == "TOR" ~ abs(arenaAdjustedXCord),
                                        teamCode != "TOR" ~ -abs(arenaAdjustedXCord),
                                        TRUE ~ arenaAdjustedXCord)) %>% 
  mutate(arenaAdjustedYCord = arenaAdjustedYCord * -1)

wsh %>% 
  ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord)) +
  stat_density2d(aes(fill = ..level..), geom = 'polygon', h =15) +
  scale_fill_viridis(option = "plasma") +
  gg_rink(side = "right") +
  gg_rink(side = "left") +
  geom_point(color = "yellow", alpha = 0.2) +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(title = "TOR Vs. WSH, Shots Heatmap", subtitle = "Data from Moneypuck", caption = "Chart by @MackinawStats") +
  annotate(geom = "text",
           x = 30, y = 51, size = 4,
           label = "Toronto Shots For", hjust = 0, family = "IBM Plex Sans") +
  theme(legend.position = "none") +
  annotate(geom = "text",
           x = -80, y = 51, size = 4,
           label = "Washington Shots For", hjust = 0, family = "IBM Plex Sans") +
  theme(legend.position = "none")

ggsave("heatmap1016.pdf")
```

```{r}
bos = shots %>% 
  filter(game_id == 20115) %>% 
  mutate(arenaAdjustedXCord = case_when(teamCode == "TOR" ~ abs(arenaAdjustedXCord),
                                        teamCode != "TOR" ~ -abs(arenaAdjustedXCord),
                                        TRUE ~ arenaAdjustedXCord)) %>% 
  mutate(arenaAdjustedYCord = arenaAdjustedYCord * -1)

bos %>% 
  ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord)) +
  stat_density2d(aes(fill = ..level..), geom = 'polygon', h =15) +
  scale_fill_viridis(option = "plasma") +
  gg_rink(side = "right") +
  gg_rink(side = "left") +
  geom_point(color = "yellow", alpha = 0.2) +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(title = "TOR Vs. BOS, Shots Heatmap", subtitle = "Data from Moneypuck", caption = "Chart by @MackinawStats") +
  annotate(geom = "text",
           x = 30, y = 51, size = 4,
           label = "Toronto Shots For", hjust = 0, family = "IBM Plex Sans") +
  theme(legend.position = "none") +
  annotate(geom = "text",
           x = -80, y = 51, size = 4,
           label = "Boston Shots For", hjust = 0, family = "IBM Plex Sans") +
  theme(legend.position = "none")

ggsave("heatmap1019.pdf")
```
```{r}
cbj = shots %>% 
  filter(game_id == 20129) %>% 
  mutate(arenaAdjustedXCord = case_when(teamCode == "TOR" ~ abs(arenaAdjustedXCord),
                                        teamCode != "TOR" ~ -abs(arenaAdjustedXCord),
                                        TRUE ~ arenaAdjustedXCord)) %>% 
  mutate(arenaAdjustedYCord = arenaAdjustedYCord * -1)

awayxg = cbj %>% 
  group_by(teamCode) %>% 
  summarise(sum = round(sum(xGoal),2)) %>% 
  filter(teamCode != "TOR")

leafsxg = cbj %>% 
  group_by(teamCode) %>% 
  summarise(sum = round(sum(xGoal),2)) %>% 
  filter(teamCode == "TOR")

cbj %>% 
  ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord)) +
  stat_density2d(aes(fill = ..level..), geom = 'polygon', h =15) +
  scale_fill_viridis(option = "plasma") +
  gg_rink(side = "right") +
  gg_rink(side = "left") +
  geom_point(color = "yellow", alpha = 0.2) +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(title = "TOR Vs. CBJ, Shots Heatmap", subtitle = "Data from Moneypuck", caption = "Chart by @MackinawStats") +
  annotate(geom = "text",
           x = 30, y = 47, size = 4,
           label = paste("Leafs xGoals:", leafsxg$sum), hjust = 0, family = "IBM Plex Sans") +
  theme(legend.position = "none") +
  annotate(geom = "text",
           x = -80, y = 47, size = 4,
           label = paste("Columbus xGoals:",awayxg$sum), hjust = 0, family = "IBM Plex Sans")
  theme(legend.position = "none")

ggsave("heatmap1021.pdf")
```
```{r}
bos = shots %>% 
  filter(game_id == 20133) %>% 
  mutate(arenaAdjustedXCord = case_when(teamCode == "TOR" ~ abs(arenaAdjustedXCord),
                                        teamCode != "TOR" ~ -abs(arenaAdjustedXCord),
                                        TRUE ~ arenaAdjustedXCord)) %>% 
  mutate(arenaAdjustedYCord = arenaAdjustedYCord * -1)

awayxg = bos %>% 
  group_by(teamCode) %>% 
  summarise(sum = round(sum(xGoal),2)) %>% 
  filter(teamCode != "TOR")

leafsxg = bos %>% 
  group_by(teamCode) %>% 
  summarise(sum = round(sum(xGoal),2)) %>% 
  filter(teamCode == "TOR")

bos %>% 
  ggplot(aes(arenaAdjustedXCord, arenaAdjustedYCord)) +
  stat_density2d(aes(fill = ..level..), geom = 'polygon', h =15) +
  scale_fill_viridis(option = "plasma") +
  gg_rink(side = "right") +
  gg_rink(side = "left") +
  geom_point(color = "yellow", alpha = 0.2) +
  theme(legend.position = "none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(title = "TOR Vs. BOS, Shots Heatmap", subtitle = "Data from Moneypuck", caption = "Chart by @MackinawStats") +
  annotate(geom = "text",
           x = 30, y = 47, size = 4,
           label = paste("Leafs xGoals:", leafsxg$sum), hjust = 0, family = "IBM Plex Sans") +
  theme(legend.position = "none") +
  annotate(geom = "text",
           x = -80, y = 47, size = 4,
           label = paste("Boston xGoals:",awayxg$sum), hjust = 0, family = "IBM Plex Sans")
  theme(legend.position = "none")

ggsave("heatmap1023.pdf")
```


  
