---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(here)
library(fuzzyjoin)
library(stringr)
library(ggthemes)
library(ggrepel)
library(extrafont)
library(hrbrthemes)
library(xkcd)
library(cowplot)
library(magick)
library(zoo)
library(gganimate)
library(ggimage)
library(beeswarm)
library(DescTools)
library(ggbeeswarm)
```

```{r}
## load rtweet package
library(rtweet)

## install rtweet from CRAN
install.packages("httpuv")

## load rtweet package
library(httpuv)

library(tidytext)
library(tidyverse)
library(ggthemes)
library(hrbrthemes)
```

```{r}
rt <- search_tweets(
  "Auston Matthews", n = 18000, include_rts = FALSE
)
```

```{r}
rt %>% 
  mutate(date = as.Date(created_at)) %>% 
  group_by(date) %>% 
  count() %>% 
  ggplot(aes(date,n)) +
  geom_line(size = 2) +
  theme_ipsum_rc(grid = FALSE)
  
```

```{r}
library(showtext)
library(extrafont)

font_add_google("IBM Plex Mono", "IBM Plex Mono")
font_add_google("IBM Plex Sans", "IBM Plex Sans")

showtext_auto()


```

```{r}
rt %>% 
  unnest_tokens(word, text) %>% 
  full_join(get_sentiments("bing")) %>%
  mutate(sentiment = case_when(is.na(sentiment) ~ "neutral", TRUE ~ sentiment)) %>% 
  mutate(value = case_when(sentiment == "positive" ~ 1,
                           sentiment == "negative" ~ -1,
                           sentiment == "neutral" ~ 0)) %>% 
  mutate(date = as.Date(created_at)) %>% 
  group_by(date) %>% 
  mutate(sum = cumsum(value)) %>% 
  summarize(sum = max(sum),
            n = n()) %>%
  mutate(mean = mean(sum)) %>% 
  mutate(diff = sum - mean) %>% 
  mutate(color = ifelse(diff>0, "yes","no")) %>% 
  ggplot(aes(date, diff)) +
  geom_col(aes(fill = color)) +
  theme_ipsum_rc(grid = FALSE) +
  labs(title = "Twitter Sentiment for 'Auston Matthews'", subtitle = "Positive - Negative Twitter Words by Date. From September 17th", caption = "Chart by @MackinawStats", y = "Net Positivity", x = "Date") +
  theme(legend.position = "none") +
  geom_hline(yintercept = 0, color = "grey") +
  theme(text=element_text(family="IBM Plex Sans"))

ggsave("Matty2.pdf")
```

```{r}
leafs <- search_tweets(
  "Leafs", n = 18000, include_rts = FALSE
)

leafs %>% 
  unnest_tokens(word, text) %>% 
  full_join(get_sentiments("bing")) %>%
  mutate(sentiment = case_when(is.na(sentiment) ~ "neutral", TRUE ~ sentiment)) %>% 
  mutate(value = case_when(sentiment == "positive" ~ 1,
                           sentiment == "negative" ~ -1,
                           sentiment == "neutral" ~ 0)) %>% 
  mutate(date = as.Date(created_at)) %>% 
  group_by(date) %>% 
  mutate(sum = cumsum(value)) %>% 
  summarize(sum = max(sum),
            n = n()) %>%
  mutate(mean = mean(sum)) %>% 
  mutate(diff = sum - mean) %>% 
  mutate(color = ifelse(diff>0, "yes","no")) %>% 
  ggplot(aes(date, diff)) +
  geom_col(aes(fill = color)) +
  theme_ipsum_rc(grid = FALSE) +
  labs(title = "Twitter Sentiment for 'Auston Matthews'", subtitle = "Positive - Negative Twitter Words by Date. From September 17th", caption = "Chart by @MackinawStats", y = "Net Positivity", x = "Date") +
  theme(legend.position = "none") +
  geom_hline(yintercept = 0, color = "grey") +
  theme(text=element_text(family="IBM Plex Sans"))
```

```{r}
babs <- search_tweets(
  "Babcock", n = 18000, include_rts = FALSE
)
```

```{r}
babs %>% 
  unnest_tokens(word, text) %>% 
  full_join(get_sentiments("bing")) %>%
  mutate(sentiment = case_when(is.na(sentiment) ~ "neutral", TRUE ~ sentiment)) %>% 
  mutate(date = as.Date(created_at)) %>% 
  group_by(date) %>% 
  count(sentiment) %>% 
  spread(key = "sentiment", value = "n") %>% 
  mutate(total = negative + neutral + positive) %>% 
  mutate(netpos = positive - negative) %>% 
  mutate(color = ifelse(netpos>0,"no","yes")) %>% 
  ggplot(aes(date,netpos)) +
  geom_col(aes(fill= color)) +
  a_plex_theme(grid = FALSE) +
  scale_fill_tableau() +
  labs(title = "Twitter Sentiment for Mike Babcock", subtitle = "Tweets containing 'Babcock' from 10/14", caption = "Chart by @MackinawStats", y = "Positive - Negative Words", x ="") +
  theme(legend.position = "none") +
  ylim(-200,200)

ggsave("babcocksent.pdf")  
  
```

