---
title: "season"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(fuzzyjoin)
library(stringr)
library(ggthemes)
library(ggrepel)
library(extrafont)
library(hrbrthemes)
library(xkcd)

NHL = read_csv(here("season.csv"))
```
```{r}
#just leafs - look at age and points %

NHL %>% 
  filter(Team == "Toronto Maple Leafs" | Team == "Tampa Bay Lightning" | Team == "Montreal Canadiens" | Team == "Boston Bruins" | Team == "Buffalo Sabres" | Team == "Florida Panthers" | Team == "Detroit Red Wings" | Team == "Ottawa Senators" ) %>%
  mutate(`PTS%` = `PTS%` *100) %>% 
  ggplot(aes(Year,`PTS%`, color = "#FA6866")) +
  geom_line(size = 2) +
  facet_wrap(~Team) +
  geom_hline(yintercept=56, color = "#FA6866") +
  theme_economist() +
theme(axis.line.x = element_line(size = .5, colour = "black"),
legend.position = "bottom", legend.direction = "horizontal",
legend.title = element_blank(),
plot.title = element_text(family = "Roboto Condensed"),
text = element_text(family = "Roboto Condensed")) +
guides(fill = guide_legend(reverse = T))+
  labs(x = "", y="Points Percentage")+
  theme(legend.position="none")
```

```{r}
NHL %>% 
  filter(Team == "Toronto Maple Leafs" | Team == "Tampa Bay Lightning" | Team == "Montreal Canadiens" | Team == "Boston Bruins" | Team == "Buffalo Sabres" | Team == "Florida Panthers" | Team == "Detroit Red Wings" | Team == "Ottawa Senators" ) %>% 
  ggplot(aes(Year,`AvAge`, color = Team)) +
  geom_line() +
  facet_grid(~Team) +
```

```{r}
NHL %>% 
  filter(Year == 2018) %>% 
  summarize(pointspercent = mean(`AvAge`))
```


```{r}
NHL %>% 
  filter(Team == "Toronto Maple Leafs" | Team == "Tampa Bay Lightning" | Team == "Montreal Canadiens" | Team == "Boston Bruins" | Team == "Buffalo Sabres" | Team == "Florida Panthers" | Team == "Detroit Red Wings" | Team == "Ottawa Senators" ) %>% 
  ggplot(aes(Year,`AvAge`, color = "#FA6866")) +
  geom_line(size = 2) +
  facet_wrap(~Team) +
  geom_hline(yintercept=28, color = "#FA6866") +
  theme_economist() +
theme(axis.line.x = element_line(size = .5, colour = "black"),
legend.position = "bottom", legend.direction = "horizontal",
legend.title = element_blank(),
plot.title = element_text(family = "Roboto Condensed"),
text = element_text(family = "Roboto Condensed")) +
guides(fill = guide_legend(reverse = T))+
  labs(x = "", y="Average Age")+
  scale_x_continuous(breaks=c(2000,2005, 2010, 2015, 2019)) +
  theme(legend.position="none")
```

```{r}
#percent change
NHL %>% 
  select(Team, Year, PTS) %>% 
  spread(key = Year, value = PTS) %>% 
  filter(Team == "Toronto Maple Leafs" | Team == "Tampa Bay Lightning" | Team == "Montreal Canadiens" | Team == "Boston Bruins" | Team == "Buffalo Sabres" | Team == "Florida Panthers" | Team == "Detroit Red Wings" | Team == "Ottawa Senators" ) %>% 
```

```{r}
NHL %>% 
  filter(Team == "Toronto Maple Leafs" | Team == "Tampa Bay Lightning" | Team == "Montreal Canadiens" | Team == "Boston Bruins" | Team == "Buffalo Sabres" | Team == "Florida Panthers" | Team == "Detroit Red Wings" | Team == "Ottawa Senators" ) %>% 
  mutate(PTS = round(PTS/GP*82)) %>% 
  ggplot(aes(Year, PTS, group = Team, color = Team)) +
  geom_line()

NHL %>% 
  filter(Team == "Toronto Maple Leafs") %>% 
  mutate(PTS = round(PTS/GP*82)) %>% 
  ggplot(aes(Year, PTS, group = Team, color = Team)) +
  geom_line() +
  expand_limits(y=0)
```

```{r}
NHL %>% 
  ggplot(aes(`Year`, `PTS%`)) +
  geom_density_ridges()


Leafs %>% 
  filter(playerPositionThatDidEvent == "C" | playerPositionThatDidEvent == "L" | playerPositionThatDidEvent == "R") %>% 
  mutate(shooterName = fct_reorder(shooterName, xGoal)) %>% 
  ggplot(aes(xGoal, shooterName)) +
  geom_density_ridges()
```

