---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(here)
library(fuzzyjoin)
library(stringr)
library(ggthemes)
library(ggrepel)
library(extrafont)
library(hrbrthemes)
library(xkcd)
library(cowplot)
library(magick)

NHL = read_csv(here("shots2019.csv"))
```
```{r}
NHL %>% 
  filter(teamCode == "TOR") %>% 
  group_by(game_id) %>% 
  summarize(xG = sum(xGoal)) %>% 
  mutate(game = row_number()) %>% 
  mutate(gamesbin = cut(game, c(0,5,10,15,20,25,30,35,40,45,50,Inf), labels=c("0-5","6-10","11-15","16-20","21-25","26-30","31-35","36-40","41-45","46-50","51-56"))) %>% 
  group_by(gamesbin) %>% 
  summarize(xGsum=sum(xG)) %>% 
  ggplot(aes(gamesbin,xGsum, color = "#FA6866")) +
  geom_line(group=1, size = 2) +
  geom_hline(yintercept=16.3, color = "#FA6866") +
  theme_economist() +
theme(axis.line.x = element_line(size = .5, colour = "black"),
legend.position = "bottom", legend.direction = "horizontal",
legend.title = element_blank(),
plot.title = element_text(family = "Roboto Condensed"),
text = element_text(family = "Roboto Condensed")) +
guides(fill = guide_legend(reverse = T))+
  labs(title = "Leafs Expected Goals by 5 game chunks", subtitle="Data from Moneypuck.com",x = "5 Game Chunks", y="Expected Goals")+
  theme(legend.position="none") +
  expand_limits(y=13)
  
  
```

```{r}
NHL %>% 
  filter(teamCode == "TOR") %>% 
  group_by(game_id) %>% 
  summarize(xG = sum(xGoal)) %>% 
  mutate(game = row_number()) %>% 
  mutate(gamesbin = cut(game, c(0,5,10,15,20,25,30,35,40,45,50,Inf), labels=c("0-5","6-10","11-15","16-20","21-25","26-30","31-35","36-40","41-45","46-50","51-56"))) %>% 
  group_by(gamesbin) %>% 
  summarize(xGsum=sum(xG)) %>%
  mutate(avg = mean(xGsum))
```

```{r}
NHL %>% 
  filter(teamCode == "TOR") %>% 
  group_by(game_id) %>% 
  summarize(xG = sum(xGoal)) %>% 
  mutate(game = row_number()) %>% 
  mutate(gamesbin = cut(game, c(0,5,10,15,20,25,30,35,40,45,50,Inf), labels=c("0-5","6-10","11-15","16-20","21-25","26-30","31-35","36-40","41-45","46-50","51-56"))) %>% 
  group_by(gamesbin) %>% 
  summarize(xGsum=mean(xG)) %>% 
  ggplot(aes(gamesbin,xGsum, color = "#FA6866")) +
  geom_hline(yintercept=3.19, color = "#FA6866") +
  geom_line(group=1, size = 2) +
  theme_economist() +
theme(axis.line.x = element_line(size = .5, colour = "black"),
legend.position = "bottom", legend.direction = "horizontal",
legend.title = element_blank(),
plot.title = element_text(family = "Roboto Condensed"),
text = element_text(family = "Roboto Condensed")) +
guides(fill = guide_legend(reverse = T))+
  labs(title = "Leafs Expected Goals by 5 game chunks", subtitle="Data from Moneypuck.com",x = "5 Game Chunks", y="Expected Goals")+
  theme(legend.position="none") +
  expand_limits(y=2.5)
```


```{r}
NHL %>% 
  filter(teamCode == "TOR") %>% 
  group_by(game_id) %>% 
  summarize(xG = sum(xGoal),
            goals = sum(goal)) %>% 
  mutate(game = row_number()) %>% 
  mutate(gamesbin = cut(game, c(0,5,10,15,20,25,30,35,40,45,50,Inf), labels=c("0-5","6-10","11-15","16-20","21-25","26-30","31-35","36-40","41-45","46-50","51-56"))) %>% 
  group_by(gamesbin) %>% 
  summarize(xGsum=mean(xG),
            Gsum = mean(goals)) %>%
  gather(xGsum,Gsum, key= "metric", value = "goals") %>% 
  ggplot(aes(gamesbin,goals, group = metric, color = metric)) +
  geom_line(size =2.5) +
  theme_economist() +
theme(axis.line.x = element_line(size = .5, colour = "black"),
legend.position = "bottom", legend.direction = "horizontal",
legend.title = element_blank(),
plot.title = element_text(family = "Roboto Condensed"),
text = element_text(family = "Roboto Condensed")) +
guides(fill = guide_legend(reverse = T))+
  labs(title = "Leafs Goals + Expected Goals by 5 game chunks", subtitle="Data from Moneypuck.com",x = "5 Game Chunks", y="Goals/Expected Goals")+
  theme(legend.position="none") +
  expand_limits(y=2.0)
```

```{r}
NHL %>% 
  filter(teamCode == "TOR") %>% 
  group_by(game_id) %>% 
  summarize(xG = sum(xGoal)) %>% 
  mutate(game = row_number()) %>% 
  mutate(gamesbin = cut(game, c(0,5,10,15,20,25,30,35,40,45,50,Inf), labels=c("0-5","6-10","11-15","16-20","21-25","26-30","31-35","36-40","41-45","46-50","51-56"))) %>% 
  group_by(gamesbin) %>% 
  summarize(xGsum=mean(xG)) %>% 
  mutate(mean(xGsum))
```

```{r}
Leafs = NHL %>% 
  filter(awayTeamCode == "TOR" | homeTeamCode == "TOR")

#Adding in counting game Id
Leafs %>% 
  mutate(game = group_indices(Leafs, game_id)) %>% 
  mutate(awayflag = if_else(teamCode != "TOR", "Opposition", "TOR")) %>% 
   group_by(game, awayflag) %>% 
  summarize(xG = sum(xGoal)) %>% 
  mutate(gamesbin = cut(game, c(0,5,10,15,20,25,30,35,40,45,50,Inf), labels=c("0-5","6-10","11-15","16-20","21-25","26-30","31-35","36-40","41-45","46-50","51-56"))) %>% 
  group_by(gamesbin, awayflag) %>% 
  summarize(xG = mean(xG)) %>% 
  ggplot(aes(gamesbin,xG, group = awayflag, color = awayflag)) +
  geom_line(size = 2.5) +
  theme_economist() +
theme(axis.line.x = element_line(size = .5, colour = "black"),
legend.position = "bottom", legend.direction = "horizontal",
legend.title = element_blank(),
plot.title = element_text(family = "Roboto Condensed"),
text = element_text(family = "Roboto Condensed")) +
guides(fill = guide_legend(reverse = T))+
  labs(title = "Leafs Expected Goals For/Against by 5 game chunks", subtitle="Data from Moneypuck.com",x = "5 Game Chunks", y="Expected Goals")+
  theme(legend.position="none") +
  expand_limits(y=1.8)
  
  

NHL %>% 
  filter(awayTeamCode == "TOR" | homeTeamCode == "TOR") %>% 
  mutate(awayflag = if_else(teamCode != "TOR", "Opposition", "TOR")) %>% 
  group_by(game_id, awayflag) %>% 
  summarize(xG = sum(xGoal)) %>% 
  ggplot(aes(game_id,xG, group = awayflag, color = awayflag)) +
  geom_line()
```

```{r}
Leafs %>% 
  mutate(game = group_indices(Leafs, game_id)) %>% 
  mutate(awayflag = if_else(teamCode != "TOR", "Opposition", "TOR")) %>% 
   group_by(game, awayflag) %>% 
  summarize(xG = sum(xGoal)) %>% 
  mutate(gamesbin = cut(game, c(0,5,10,15,20,25,30,35,40,45,50,Inf), labels=c("0-5","6-10","11-15","16-20","21-25","26-30","31-35","36-40","41-45","46-50","51-56"))) %>% 
  group_by(gamesbin, awayflag) %>% 
  summarize(xG = mean(xG)) %>% 
  spread(key = awayflag, value = xG) %>% 
  mutate(diff = TOR - Opposition) %>% 
  ggplot(aes(gamesbin, diff, group = 1, color = "#FA6866")) +
  geom_line(size = 2.5) +
  expand_limits(y=-1.0) +
  geom_hline(yintercept=0.0, color = "#1B55E3", size = 1.3) +
  theme_economist() +
theme(axis.line.x = element_line(size = .5, colour = "black"),
legend.position = "bottom", legend.direction = "horizontal",
legend.title = element_blank(),
plot.title = element_text(family = "Roboto Condensed"),
text = element_text(family = "Roboto Condensed")) +
guides(fill = guide_legend(reverse = T))+
  labs(title = "Leafs Expected Goals Differential by 5 game chunks", subtitle="Data from Moneypuck.com",x = "5 Game Chunks", y="Expected Goal Differential")+
  theme(legend.position="none")
```

```{r}
TBL = NHL %>% 
  filter(awayTeamCode == "T.B" | homeTeamCode == "T.B") 
  
TBL %>% 
  filter(awayTeamCode == "T.B" | homeTeamCode == "T.B") %>% 
  mutate(game = group_indices(TBL, game_id)) %>% 
  mutate(awayflag = if_else(teamCode != "T.B", "Opposition", "T.B")) %>% 
   group_by(game, awayflag) %>% 
  summarize(xG = sum(xGoal)) %>% 
  mutate(gamesbin = cut(game, c(0,5,10,15,20,25,30,35,40,45,50,Inf), labels=c("0-5","6-10","11-15","16-20","21-25","26-30","31-35","36-40","41-45","46-50","51-56"))) %>% 
  group_by(gamesbin, awayflag) %>% 
  summarize(xG = mean(xG)) %>% 
  spread(key = awayflag, value = xG) %>% 
  mutate(diff = T.B - Opposition)
```


