---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggchicklet)
library(hrbrthemes)
library(ggthemes)
```

```{r}
new = read_csv("backs.csv")
```

```{r}
cleaned = new %>% 
  select(`Player`, `S`, `S Back`, `S Dflect`, `S Slap`, `S Snap`, `S Tip`, `S Wrap`, `S Wrist`) %>% 
  mutate(Backhand = (`S Back`/S) *100,
         Deflect = (`S Dflect`/S) *100,
         Slapshot = (`S Slap`/S) *100,
         Snapshot = (`S Snap`/S) *100,
         Tip = (`S Tip`/S) *100,
         Wrap= (`S Wrap`/S) *100,
         Wrist = (`S Wrist`/S) *100) %>% 
  filter(S>100) %>% 
  select(Player,Backhand,Slapshot, Snapshot, Tip, Wrap, Wrist) 

cleaned %>% 
  mutate(Player = fct_reorder(Player, Wrist)) %>% 
  gather(Backhand:Wrist, key = "shot_type", value = "percent") %>% 
  mutate(shot_type = factor(shot_type, levels = c("Wrist", "Snapshot", "Backhand", "Tip", "Slapshot","Wrap"))) %>% 
  ggplot(aes(Player, percent, fill = shot_type)) +
  geom_chicklet() +
  coord_flip() +
   theme_ipsum_rc(grid = "X") +
  theme(legend.position = "top") +
  scale_fill_tableau() +
  labs(title = "Leafs Shot Type Tendencies", fill = "Shot Type", subtitle = "Data from NHL.com", caption = "Chart by @MackinawStats", y = "Percent", x= "") +
  guides(fill = guide_legend(nrow = 1))
```
```{r}
cleaned %>% 
  mutate(Player = fct_reorder(Player, Wrist)) %>% 
  gather(Backhand:Wrist, key = "shot_type", value = "percent") %>% 
  mutate(shot_type = factor(shot_type, levels = c("Wrist", "Snapshot", "Backhand", "Tip", "Slapshot","Wrap"))) %>% 
  ggplot(aes(Player, percent, fill = shot_type)) +
  geom_chicklet() +
  coord_flip() +
   theme_ipsum_rc(grid = "X") +
  theme(legend.position = "top") +
  scale_fill_tableau() +
  labs(title = "Leafs Shot Type Tendencies", fill = "Shot Type", subtitle = "Data from NHL.com", caption = "Chart by @MackinawStats", y = "Percent", x= "") +
  guides(fill = guide_legend(nrow = 1)) +
  facet_wrap(~shot_type)

ggsave("leafsshots.png")
```

```{r}
cleaned %>% 
  mutate(Player = fct_reorder(Player, Wrist)) %>% 
  gather(Backhand:Wrist, key = "shot_type", value = "percent") %>% 
  mutate(shot_type = factor(shot_type, levels = c("Wrist", "Snapshot", "Backhand", "Tip", "Slapshot","Wrap"))) %>% 
  ggplot(aes(Player, percent, fill = shot_type)) +
  geom_chicklet() +
  coord_flip() +
   theme_ipsum_rc(grid = "X") +
  theme(legend.position = "none") +
  scale_fill_tableau() +
  labs(title = "Leafs Shot Type Tendencies", fill = "Shot Type", subtitle = "Data from NHL.com", caption = "Chart by @MackinawStats", y = "Percent", x= "") +
  guides(fill = guide_legend(nrow = 1)) +
  facet_wrap(~shot_type) +
  geom_text(aes(label = paste0(round(percent),"%"), hjust = -0.05)) +
  ylim(0,75)

ggsave("leafsshotswithpercent.png")
```


