---
title: "spider charts leafs"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(fuzzyjoin)
library(stringr)
library(ggthemes)
library(ggrepel)
library(extrafont)
library(hrbrthemes)
library(fmsb)


```

```{r}

# Create data: note in High school for Jonathan:
data=as.data.frame(matrix( sample( 2:20 , 10 , replace=T) , ncol=10))
colnames(data)=c("math" , "english" , "biology" , "music" , "R-coding", "data-viz" , "french" , "physic", "statistic", "sport" )
 
# To use the fmsb package, I have to add 2 lines to the dataframe: the max and min of each topic to show on the plot!
data=rbind(rep(20,10) , rep(0,10) , data)
 
# The default radar chart proposed by the library:
radarchart(data)
 
# Custom the radarChart !
radarchart( data  , axistype=1 , 
 
    #custom polygon
    pcol=rgb(0.2,0.5,0.5,0.9) , pfcol=rgb(0.2,0.5,0.5,0.5) , plwd=4 , 
 
    #custom the grid
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,20,5), cglwd=0.8,
 
    #custom labels
    vlcex=0.8 
    )
```
```{r}
radar = read_csv(here("leafs radar.csv"), na = c("--","NA")) %>% 
  filter(Player == "Jake Gardiner") %>% 
  select(xGA, CA, GA, xGF, CF, GF)

max<-c(45,900,40,45,950,65)
min<-c(8,200,8,8,200,5)

radar_chart <- rbind(max,min,radar)


radarchart( radar_chart , axistype=1 , 
 
    #custom polygon
    pcol=rgb(0.2,0.5,0.5,0.9) , pfcol=rgb(0.2,0.5,0.5,0.5) , plwd=4 , 
 
    #custom the grid
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,20,5), cglwd=0.8,
 
    #custom labels
    vlcex=0.8 
    )

```

```{r}
radar = read_csv(here("leafs radar.csv"), na = c("--","NA")) %>% 
  filter(Player == "Frederik Gauthier") %>% 
  select(xGA, CA, GA, xGF, CF, GF)

max<-c(45,900,40,45,950,65)
min<-c(8,200,8,8,200,5)

radar_chart <- rbind(max,min,radar)


radarchart( radar_chart , axistype=1 , 
 
    #custom polygon
    pcol=rgb(0.2,0.5,0.5,0.9) , pfcol=rgb(0.2,0.5,0.5,0.5) , plwd=4 , 
 
    #custom the grid
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,20,5), cglwd=0.8,
 
    #custom labels
    vlcex=0.8 
    )

```

```{r}
radar = read_csv(here("leafs radar.csv"), na = c("--","NA")) %>% 
  filter(Player == "Andreas Johnsson" | Player == "Auston Matthews" | Player == "Kasperi Kapanen") %>% 
  select(xGA, CA, GA, xGF, CF, GF)

max<-c(45,900,40,45,950,65)
min<-c(8,200,8,8,200,5)

radar_chart <- rbind(max,min,radar)


colors_border=c( rgb(0.2,0.5,0.5,0.9), rgb(0.8,0.2,0.5,0.9) , rgb(0.7,0.5,0.1,0.9) )
colors_in=c( rgb(0.2,0.5,0.5,0.4), rgb(0.8,0.2,0.5,0.4) , rgb(0.7,0.5,0.1,0.4) )
radarchart( radar_chart , axistype=1 , 
    #custom polygon
    pcol=colors_border , pfcol=colors_in , plwd=4 , plty=1,
    #custom the grid
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,20,5), cglwd=0.8,
    #custom labels
    vlcex=0.8 
    )
legend(x=0.7, y=1, legend = rownames(radar_chart[-c(1,2),]), bty = "n", pch=20 , col=colors_in , text.col = "grey", cex=1.2, pt.cex=3)

```


