---
title: "Tavares Charts"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(fuzzyjoin)
library(stringr)
library(ggthemes)
library(ggrepel)
library(extrafont)
library(hrbrthemes)

NHL = read_csv(here("NHL.csv"), na = c("--","NA"))
```
#Tavares chart 1
```{r}
fill <- c("#00a3dc","#01526d")

NHL %>% 
  filter(Player == "John Tavares") %>% 
  ggplot(aes(Season,`P/60`, fill ="blue4")) +
geom_col() +
geom_text(aes(label = `P/60`), position = position_stack(vjust = 0.5),
colour = "white", size = 3, family = "Roboto Condensed",
show.legend = F) +
scale_x_continuous(breaks = seq(2010,2019,1)) +
labs(title = "John Tavares P/60",
subtitle = "By year") +
labs(x = "Year", y = "P/60") +
  theme_economist() + scale_fill_manual(values = fill) +
theme(axis.line.x = element_line(size = .5, colour = "black"),
legend.position = "bottom", legend.direction = "horizontal",
legend.title = element_blank(),
plot.title = element_text(family = "Roboto Condensed"),
text = element_text(family = "Roboto Condensed")) +
guides(fill = guide_legend(reverse = T))+
  theme(legend.position="none")

```
#Tavares chart 2
```{r}
#prorating statistics
NHL %>% 
  filter(Player == "John Tavares") %>% 
  mutate(G = (G/GP)*82) %>% 
  mutate(G=round(G)) %>% 
  ggplot(aes(Season,G,fill = "blue4")) +
geom_col() +
geom_text(aes(label = `G`), position = position_stack(vjust = 0.5),
colour = "white", size = 3, family = "Roboto Condensed",
show.legend = F) +
scale_x_continuous(breaks = seq(2010,2019,1)) +
labs(title = "John Tavares 5v5 Goals",
subtitle = "By year, prorated for 82 games in all seasons") +
labs(x = "Year", y = "G") +
  theme_economist() + scale_fill_manual(values = fill) +
theme(axis.line.x = element_line(size = .5, colour = "black"),
legend.position = "bottom", legend.direction = "horizontal",
legend.title = element_blank(),
plot.title = element_text(family = "Roboto Condensed"),
text = element_text(family = "Roboto Condensed")) +
guides(fill = guide_legend(reverse = T))+
  theme(legend.position="none")

```
#Tavares chart 3
```{r}
#prorating statistics
NHL %>% 
  filter(Player == "John Tavares") %>% 
  mutate(P = (P/GP)*82) %>% 
  mutate(P=round(P)) %>% 
  ggplot(aes(Season,P, fill = "blue4")) +
geom_col() +
geom_text(aes(label = `P`), position = position_stack(vjust = 0.5),
colour = "white", size = 3, family = "Roboto Condensed",
show.legend = F) +
scale_x_continuous(breaks = seq(2010,2019,1)) +
labs(title = "John Tavares 5v5 Points",
subtitle = "By year, prorated for 82 games in all seasons") +
labs(x = "Year", y = "P") +
  theme_economist() + scale_fill_manual(values = fill) +
theme(axis.line.x = element_line(size = .5, colour = "black"),
legend.position = "bottom", legend.direction = "horizontal",
legend.title = element_blank(),
plot.title = element_text(family = "Roboto Condensed"),
text = element_text(family = "Roboto Condensed")) +
guides(fill = guide_legend(reverse = T))+
  theme(legend.position="none")
```
