---
title: "tulloch"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(fuzzyjoin)
library(stringr)
library(ggthemes)
library(ggrepel)
library(extrafont)
library(hrbrthemes)
library(xkcd)
library(cowplot)
library(magick)
library(zoo)
library(gganimate)
library(ggimage)
library(beeswarm)
library(ggbeeswarm)

nhl = read_csv("tulloch.csv") %>% 
  filter(GP>40) %>% 
  mutate(pointspergame = Points/GP)
```

```{r}
marner = filter(nhl, player == "MITCH.MARNER")
kane = nhl %>% 
  filter(player == "PATRICK.KANE") %>% 
  filter(season == "20072008" | season == "20082009" | season == "20092010")
tarasenko = nhl %>% 
  filter(player == "VLADIMIR.TARASENKO") %>% 
  filter(season == "20132014" | season == "20142015")
gudreau = nhl %>% 
  filter(player == "JOHNNY.GAUDREAU") %>% 
  filter(season == "20142015" | season == "20152016")
pasta = nhl %>% 
  filter(player == "DAVID.PASTRNAK") %>% 
  filter(season == "20142015" | season == "20152016" | season == "20162017")
dry = nhl %>% 
  filter(player == "LEON.DRAISAITL") %>% 
  filter(season == "20152016" | season == "20162017")



nhl %>% 
  ggplot(aes(season,pointspergame)) +
  geom_quasirandom(dodge.width = 1, alpha = 0.1) +
  geom_point(data = marner, color = "#003E7E", size = 3, alpha = 1) +
  geom_point(data = kane, color = "#CF0A2C", size = 3, alpha = 1) +
  geom_point(data = tarasenko, color = "#002F87", size = 3, alpha = 1) +
  geom_point(data = gudreau, color = "#C8102E", size = 3, alpha = 1) +
  geom_point(data = pasta, color = "#FFB81C", size = 3, alpha = 1) +
  geom_point(data = dry, color = "#FF4C00", size = 3, alpha = 1) +
  geom_line(data = marner, alpha = 0.5, linetype = 'dashed') +
  geom_line(data = kane, alpha = 0.5, linetype = 'dashed') +
  geom_line(data = tarasenko, alpha = 0.5, linetype = 'dashed') +
  geom_line(data = gudreau, alpha = 0.5, linetype = 'dashed') +
  geom_line(data = pasta, alpha = 0.5, linetype = 'dashed') +
  geom_line(data = dry, alpha = 0.5, linetype = 'dashed') +
  theme_fivethirtyeight() +
  labs(title = "Mitch Marner comparables from 2010", subtitle ="data from Evolving Hockey, GP>40") +
  scale_x_continuous(breaks = c(20072008, 20092010, 20112012, 20132014, 20152016, 20172018, 20182019), labels = c("2008", "2010", "2012", "2014", "2016", "2018", "2019"))
  
```

